import type { CampaignPreset } from './types'

const colonialRivals = ['britain', 'france', 'spain', 'portugal', 'netherlands', 'unitedStates'] as const

export const campaignPresets: CampaignPreset[] = [
  {
    id: 'british-scramble',
    factionId: 'britain',
    title: 'Rule Britannia',
    subtitle: 'Colonial scramble · 1836',
    startYear: 1836,
    homeRegionId: 'british-isles',
    treasuryLabel: 'TREASURY',
    treasuryPrefix: '£',
    legitimacyLabel: 'LEGITIMACY',
    resources: { treasury: 3200, supply: 78, influence: 68, legitimacy: 80, industry: 62, rawStock: 40, manufactures: 28 },
    tradePartners: ['south-china'],
    rivalIds: ['france', 'spain', 'portugal', 'netherlands', 'unitedStates'],
    objectiveTitle: 'Plant the flag',
    objectiveBody: 'Hold eight colonies outside the British Isles',
    objectiveTarget: 8,
    objectiveMetric: 'colonies',
    doctrine: 'Professional expeditionary columns and naval logistics',
    campaignSummary:
      'Race France, Spain, Portugal, the Dutch, and the United States for colonies. Ship raw materials home, industrialize the mills, and sell finished goods back into colonial markets.',
    warActionLabel: 'Dispatch column',
  },
  {
    id: 'french-scramble',
    factionId: 'france',
    title: 'Mission Civilisatrice',
    subtitle: 'Colonial scramble · 1836',
    startYear: 1836,
    homeRegionId: 'france',
    treasuryLabel: 'TRÉSOR',
    treasuryPrefix: '£',
    legitimacyLabel: 'PRESTIGE',
    resources: { treasury: 2980, supply: 74, influence: 64, legitimacy: 76, industry: 55, rawStock: 32, manufactures: 22 },
    tradePartners: [],
    rivalIds: ['britain', 'spain', 'portugal', 'netherlands', 'unitedStates'],
    objectiveTitle: 'Expand the empire',
    objectiveBody: 'Hold seven colonies outside metropolitan France',
    objectiveTarget: 7,
    objectiveMetric: 'colonies',
    doctrine: 'Massed artillery and Armée d’Afrique columns',
    campaignSummary:
      'Contest Algeria, West Africa, and the wider scramble. Feed French workshops with colonial raw goods and flood overseas markets with manufactures.',
    warActionLabel: 'Order the advance',
  },
  {
    id: 'spanish-scramble',
    factionId: 'spain',
    title: 'The Remaining Empire',
    subtitle: 'Colonial scramble · 1836',
    startYear: 1836,
    homeRegionId: 'spain',
    treasuryLabel: 'TESORO',
    treasuryPrefix: '£',
    legitimacyLabel: 'CROWN AUTHORITY',
    resources: { treasury: 2420, supply: 66, influence: 52, legitimacy: 68, industry: 38, rawStock: 36, manufactures: 18 },
    tradePartners: [],
    rivalIds: ['britain', 'france', 'portugal', 'netherlands', 'unitedStates'],
    objectiveTitle: 'Hold and reclaim',
    objectiveBody: 'Hold six colonies outside Spain',
    objectiveTarget: 6,
    objectiveMetric: 'colonies',
    doctrine: 'Colonial garrisons and regional line armies',
    campaignSummary:
      'Defend Cuba and the Philippines while racing rivals for new claims. Silver, sugar, and tobacco must feed Spanish industry and return as finished goods.',
    warActionLabel: 'Raise the tercio',
  },
  {
    id: 'portuguese-scramble',
    factionId: 'portugal',
    title: 'The Old Sea Road',
    subtitle: 'Colonial scramble · 1836',
    startYear: 1836,
    homeRegionId: 'portugal',
    treasuryLabel: 'ERÁRIO',
    treasuryPrefix: '£',
    legitimacyLabel: 'CROWN AUTHORITY',
    resources: { treasury: 2180, supply: 70, influence: 48, legitimacy: 72, industry: 34, rawStock: 30, manufactures: 14 },
    tradePartners: [],
    rivalIds: ['britain', 'france', 'spain', 'netherlands', 'unitedStates'],
    objectiveTitle: 'African littoral',
    objectiveBody: 'Hold six colonies outside Portugal',
    objectiveTarget: 6,
    objectiveMetric: 'colonies',
    doctrine: 'Coastal presidios and Atlantic resupply',
    campaignSummary:
      'Hold Angola, Mozambique, and the East African coast while rivals close in. Ivory and coastal trade must industrialize Lisbon’s workshops.',
    warActionLabel: 'Reinforce the presidio',
  },
  {
    id: 'dutch-scramble',
    factionId: 'netherlands',
    title: 'Company Dominion',
    subtitle: 'Colonial scramble · 1836',
    startYear: 1836,
    homeRegionId: 'low-countries',
    treasuryLabel: 'COMPANY CHEST',
    treasuryPrefix: '£',
    legitimacyLabel: 'DIRECTORS’ CONFIDENCE',
    resources: { treasury: 2760, supply: 72, influence: 58, legitimacy: 74, industry: 50, rawStock: 44, manufactures: 26 },
    tradePartners: [],
    rivalIds: ['britain', 'france', 'spain', 'portugal', 'unitedStates'],
    objectiveTitle: 'Spice & sugar',
    objectiveBody: 'Hold six colonies outside the Low Countries',
    objectiveTarget: 6,
    objectiveMetric: 'colonies',
    doctrine: 'Company garrisons and fortified plantation districts',
    campaignSummary:
      'Defend Java and the Guianas while racing European rivals. Spices and sugar feed Dutch mills; finished goods return to colonial markets.',
    warActionLabel: 'Authorize expedition',
  },
  {
    id: 'manifest-destiny',
    factionId: 'unitedStates',
    title: 'Manifest Destiny',
    subtitle: 'Continental scramble · 1846',
    startYear: 1846,
    homeRegionId: 'atlantic-seaboard',
    treasuryLabel: 'TREASURY',
    treasuryPrefix: '$',
    legitimacyLabel: 'MANDATE',
    resources: { treasury: 2680, supply: 76, influence: 58, legitimacy: 74, industry: 48, rawStock: 35, manufactures: 20 },
    tradePartners: [],
    rivalIds: ['britain', 'france', 'spain', 'mexico', 'lakota'],
    objectiveTitle: 'Continental claim',
    objectiveBody: 'Control seven North American regions',
    objectiveTarget: 7,
    objectiveMetric: 'regions',
    doctrine: 'Volunteer armies, dragoons, and concentrated field artillery',
    campaignSummary:
      'Push from the Atlantic through the Ohio and Mississippi into the Plains and Pacific—while Britain, France, and Spain contest the wider colonial scramble. Cotton and timber feed northern mills; manufactures return west.',
    warActionLabel: 'Plan campaign',
  },
  {
    id: 'lakota-resistance',
    factionId: 'lakota',
    title: 'The Northern Plains',
    subtitle: 'Lakota sovereignty · 1846',
    startYear: 1846,
    homeRegionId: 'northern-plains',
    treasuryLabel: 'TRADE STORES',
    treasuryPrefix: '',
    legitimacyLabel: 'COHESION',
    resources: { treasury: 1640, supply: 82, influence: 64, legitimacy: 86, industry: 12, rawStock: 20, manufactures: 8 },
    tradePartners: [],
    rivalIds: ['unitedStates', 'britain', 'mexico'],
    objectiveTitle: 'Defend the buffalo roads',
    objectiveBody: 'Hold or reclaim three North American regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Mounted maneuver, dispersed camps, and attacks on supply lines',
    campaignSummary:
      'Unite the oyáte against expanding settler and colonial powers. Mobility is your greatest military advantage against gunpowder armies.',
    warActionLabel: 'Call the akíčhita',
  },
  {
    id: 'zulu-sovereignty',
    factionId: 'zulu',
    title: 'The Royal Amabutho',
    subtitle: 'Zulu sovereignty · 1836',
    startYear: 1836,
    homeRegionId: 'zulu-kingdom',
    treasuryLabel: 'ROYAL HERDS',
    treasuryPrefix: '',
    legitimacyLabel: 'ROYAL AUTHORITY',
    resources: { treasury: 1760, supply: 88, influence: 48, legitimacy: 90, industry: 10, rawStock: 18, manufactures: 6 },
    tradePartners: [],
    rivalIds: ['britain', 'portugal', 'france'],
    objectiveTitle: 'Guard the amakhanda',
    objectiveBody: 'Control three southern African regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Disciplined amabutho using the horns of the buffalo formation',
    campaignSummary:
      'Muster age-regiments and meet colonial musket columns on ground of your choosing before the scramble closes the frontier.',
    warActionLabel: 'Muster amabutho',
  },
  {
    id: 'ashanti-sovereignty',
    factionId: 'ashanti',
    title: 'The Golden Stool',
    subtitle: 'Asante sovereignty · 1836',
    startYear: 1836,
    homeRegionId: 'gold-coast',
    treasuryLabel: 'GOLD RESERVE',
    treasuryPrefix: '',
    legitimacyLabel: 'STOOL AUTHORITY',
    resources: { treasury: 2420, supply: 79, influence: 67, legitimacy: 91, industry: 18, rawStock: 28, manufactures: 10 },
    tradePartners: ['sokoto'],
    rivalIds: ['britain', 'france', 'portugal'],
    objectiveTitle: 'Forest dominion',
    objectiveBody: 'Control four African regions',
    objectiveTarget: 4,
    objectiveMetric: 'regions',
    doctrine: 'Long Dane musketry and enveloping wings in dense forest',
    campaignSummary:
      'Defend the forest roads and gold trade as European powers race to claim the West African coast.',
    warActionLabel: 'Muster the asafo',
  },
]

export const defaultCampaign = campaignPresets[0]

export { colonialRivals }
