import type { CampaignPreset } from './types'

export const campaignPresets: CampaignPreset[] = [
  {
    id: 'manifest-destiny',
    factionId: 'unitedStates',
    title: 'Manifest Destiny',
    subtitle: 'Continental expansion · 1846',
    startYear: 1846,
    homeRegionId: 'american-republic',
    treasuryLabel: 'TREASURY',
    treasuryPrefix: '$',
    legitimacyLabel: 'MANDATE',
    resources: { treasury: 2180, supply: 70, influence: 55, legitimacy: 71 },
    tradePartners: [],
    rivalIds: ['mexico', 'lakota', 'haudenosaunee'],
    objectiveTitle: 'Continental claim',
    objectiveBody: 'Control four North American regions',
    objectiveTarget: 4,
    objectiveMetric: 'regions',
    doctrine: 'Volunteer armies, dragoons, and concentrated field artillery',
    campaignSummary:
      'Carry the expansionist program of 1845 westward through diplomacy or war. Mexican sovereignty, treaty nations, and powerful Indigenous polities stand in the path—and every conquest raises resistance.',
    warActionLabel: 'Plan campaign',
  },
  {
    id: 'imperial-rivalry',
    factionId: 'britain',
    title: 'The Great Game',
    subtitle: 'Imperial rivalry · 1836',
    startYear: 1836,
    homeRegionId: 'gold-coast',
    treasuryLabel: 'TREASURY',
    treasuryPrefix: '£',
    legitimacyLabel: 'LEGITIMACY',
    resources: { treasury: 2860, supply: 74, influence: 61, legitimacy: 78 },
    tradePartners: ['south-china'],
    rivalIds: ['france', 'portugal', 'netherlands'],
    objectiveTitle: 'Commercial footholds',
    objectiveBody: 'Sign three reciprocal trade accords',
    objectiveTarget: 3,
    objectiveMetric: 'accords',
    doctrine: 'Professional expeditionary columns supported by naval logistics',
    campaignSummary:
      'Compete with European rivals for markets and influence while balancing supply, parliamentary legitimacy, and the sovereignty of established nations.',
    warActionLabel: 'Convene council',
  },
  {
    id: 'lakota-resistance',
    factionId: 'lakota',
    title: 'The Northern Plains',
    subtitle: 'Lakota sovereignty · 1846',
    startYear: 1846,
    homeRegionId: 'northern-plains',
    treasuryLabel: 'TRADE STORES',
    treasuryPrefix: '',
    legitimacyLabel: 'COHESION',
    resources: { treasury: 1640, supply: 82, influence: 64, legitimacy: 86 },
    tradePartners: [],
    rivalIds: ['unitedStates', 'britain', 'mexico'],
    objectiveTitle: 'Defend the buffalo roads',
    objectiveBody: 'Hold or reclaim three North American regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Mounted maneuver, dispersed camps, and attacks on supply lines',
    campaignSummary:
      'Unite the oyáte, preserve access to the buffalo ranges, and build alliances against expanding settler states. Mobility is your greatest military advantage.',
    warActionLabel: 'Call the akíčhita',
  },
  {
    id: 'haudenosaunee-resistance',
    factionId: 'haudenosaunee',
    title: 'The Great Law',
    subtitle: 'Haudenosaunee diplomacy · 1846',
    startYear: 1846,
    homeRegionId: 'eastern-woodlands',
    treasuryLabel: 'CONFEDERACY STORES',
    treasuryPrefix: '',
    legitimacyLabel: 'COUNCIL UNITY',
    resources: { treasury: 1580, supply: 68, influence: 82, legitimacy: 88 },
    tradePartners: ['great-lakes'],
    rivalIds: ['unitedStates', 'britain', 'france'],
    objectiveTitle: 'Renew the covenant chain',
    objectiveBody: 'Build three durable alliances',
    objectiveTarget: 3,
    objectiveMetric: 'accords',
    doctrine: 'Woodland marksmanship, concealment, and prepared withdrawals',
    campaignSummary:
      'Use the Confederacy’s diplomatic tradition and woodland expertise to preserve treaty boundaries, unite neighboring nations, and resist further dispossession.',
    warActionLabel: 'Raise defenders',
  },
  {
    id: 'ashanti-sovereignty',
    factionId: 'ashanti',
    title: 'The Golden Stool',
    subtitle: 'Asante sovereignty · 1836',
    startYear: 1836,
    homeRegionId: 'gold-coast',
    treasuryLabel: 'GOLD RESERVE',
    treasuryPrefix: '',
    legitimacyLabel: 'STOOL AUTHORITY',
    resources: { treasury: 2420, supply: 79, influence: 67, legitimacy: 91 },
    tradePartners: ['sokoto'],
    rivalIds: ['britain', 'france', 'portugal'],
    objectiveTitle: 'Forest alliance',
    objectiveBody: 'Secure three African regions or accords',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Long Dane musketry and enveloping wings in dense forest',
    campaignSummary:
      'Defend the forest roads, preserve control of the gold trade, and prevent coastal forts from becoming a path to foreign occupation.',
    warActionLabel: 'Muster the asafo',
  },
  {
    id: 'zulu-sovereignty',
    factionId: 'zulu',
    title: 'The Royal Amabutho',
    subtitle: 'Zulu sovereignty · 1836',
    startYear: 1836,
    homeRegionId: 'zulu-kingdom',
    treasuryLabel: 'ROYAL HERDS',
    treasuryPrefix: '',
    legitimacyLabel: 'ROYAL AUTHORITY',
    resources: { treasury: 1760, supply: 88, influence: 48, legitimacy: 90 },
    tradePartners: [],
    rivalIds: ['britain', 'portugal', 'kongo'],
    objectiveTitle: 'Guard the amakhanda',
    objectiveBody: 'Control three southern African regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Disciplined amabutho using the horns of the buffalo formation',
    campaignSummary:
      'Muster age-regiments through the royal amakhanda, secure cattle country, and meet expanding colonial frontiers on ground of your choosing.',
    warActionLabel: 'Muster amabutho',
  },
  {
    id: 'khalsa-frontier',
    factionId: 'sikh',
    title: 'The Khalsa Frontier',
    subtitle: 'Sikh Empire · 1836',
    startYear: 1836,
    homeRegionId: 'punjab',
    treasuryLabel: 'LAHORE TREASURY',
    treasuryPrefix: '',
    legitimacyLabel: 'KHALSA UNITY',
    resources: { treasury: 2680, supply: 84, influence: 59, legitimacy: 87 },
    tradePartners: [],
    rivalIds: ['britain', 'maratha', 'qing'],
    objectiveTitle: 'Secure the five rivers',
    objectiveBody: 'Control three Indian regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'French-drilled infantry, Lahore muskets, cavalry, and horse artillery',
    campaignSummary:
      'Modernize the Khalsa army, balance the frontier courts, and prevent the East India Company from enclosing the Punjab.',
    warActionLabel: 'Call the Khalsa',
  },
  {
    id: 'mapuche-resistance',
    factionId: 'mapuche',
    title: 'Wallmapu Endures',
    subtitle: 'Mapuche sovereignty · 1846',
    startYear: 1846,
    homeRegionId: 'mapuche-country',
    treasuryLabel: 'EXCHANGE STORES',
    treasuryPrefix: '',
    legitimacyLabel: 'LOF UNITY',
    resources: { treasury: 1510, supply: 76, influence: 70, legitimacy: 89 },
    tradePartners: [],
    rivalIds: ['granColombia', 'brazil', 'britain'],
    objectiveTitle: 'Hold the frontier rivers',
    objectiveBody: 'Control three South American regions',
    objectiveTarget: 3,
    objectiveMetric: 'regions',
    doctrine: 'Malón cavalry, lances, firearms, and rapid frontier concentration',
    campaignSummary:
      'Coordinate the lof, preserve the frontier rivers, and use mounted mobility to resist encroachment from neighboring republics and empires.',
    warActionLabel: 'Gather the weichafe',
  },
]

export const defaultCampaign = campaignPresets[0]
