import type { CampaignEvent, Faction, Region } from './types'

export const factions: Record<string, Faction> = {
  unitedStates: {
    id: 'unitedStates',
    name: 'United States',
    shortName: 'United States',
    color: '#496b82',
    accent: '#b8d1df',
    kind: 'imperial',
    emblem: 'US',
  },
  britain: {
    id: 'britain',
    name: 'British Empire',
    shortName: 'Britain',
    color: '#a8413e',
    accent: '#e8b9ae',
    kind: 'imperial',
    emblem: 'BR',
  },
  france: {
    id: 'france',
    name: 'Kingdom of France',
    shortName: 'France',
    color: '#536f91',
    accent: '#bfd1de',
    kind: 'imperial',
    emblem: 'FR',
  },
  portugal: {
    id: 'portugal',
    name: 'Portuguese Crown',
    shortName: 'Portugal',
    color: '#6d7655',
    accent: '#ced3a7',
    kind: 'imperial',
    emblem: 'PT',
  },
  netherlands: {
    id: 'netherlands',
    name: 'Dutch Trading Company',
    shortName: 'Dutch Company',
    color: '#b66a3c',
    accent: '#f0bd83',
    kind: 'commercial',
    emblem: 'VOC',
  },
  haudenosaunee: {
    id: 'haudenosaunee',
    name: 'Haudenosaunee Confederacy',
    shortName: 'Haudenosaunee',
    color: '#47766d',
    accent: '#9ec1b2',
    kind: 'sovereign',
    emblem: 'HC',
  },
  coastSalish: {
    id: 'coastSalish',
    name: 'Coast Salish Nations',
    shortName: 'Coast Salish',
    color: '#486f79',
    accent: '#9fc4ca',
    kind: 'sovereign',
    emblem: 'CS',
  },
  lakota: {
    id: 'lakota',
    name: 'Lakota Oyate',
    shortName: 'Lakota',
    color: '#8f5c46',
    accent: '#d8ad82',
    kind: 'sovereign',
    emblem: 'LO',
  },
  mexico: {
    id: 'mexico',
    name: 'Mexican Republic',
    shortName: 'Mexico',
    color: '#56785e',
    accent: '#a8c09e',
    kind: 'sovereign',
    emblem: 'MX',
  },
  granColombia: {
    id: 'granColombia',
    name: 'Gran Colombian Union',
    shortName: 'Gran Colombia',
    color: '#a8863f',
    accent: '#dec789',
    kind: 'sovereign',
    emblem: 'GC',
  },
  tupinamba: {
    id: 'tupinamba',
    name: 'Amazonian River Confederacies',
    shortName: 'River Nations',
    color: '#3f7663',
    accent: '#83b19a',
    kind: 'sovereign',
    emblem: 'AR',
  },
  brazil: {
    id: 'brazil',
    name: 'Empire of Brazil',
    shortName: 'Brazil',
    color: '#79813d',
    accent: '#d0cd80',
    kind: 'sovereign',
    emblem: 'BZ',
  },
  andean: {
    id: 'andean',
    name: 'Andean Confederation',
    shortName: 'Andean Confederation',
    color: '#806455',
    accent: '#c8ad94',
    kind: 'sovereign',
    emblem: 'AC',
  },
  mapuche: {
    id: 'mapuche',
    name: 'Mapuche Confederation',
    shortName: 'Mapuche',
    color: '#4c6d83',
    accent: '#9eb6c7',
    kind: 'sovereign',
    emblem: 'MC',
  },
  sokoto: {
    id: 'sokoto',
    name: 'Sokoto Caliphate',
    shortName: 'Sokoto',
    color: '#967641',
    accent: '#d9bd7f',
    kind: 'sovereign',
    emblem: 'SK',
  },
  ashanti: {
    id: 'ashanti',
    name: 'Ashanti Empire',
    shortName: 'Ashanti',
    color: '#a36c2b',
    accent: '#e1b65d',
    kind: 'sovereign',
    emblem: 'AS',
  },
  ethiopia: {
    id: 'ethiopia',
    name: 'Ethiopian Empire',
    shortName: 'Ethiopia',
    color: '#8d4f48',
    accent: '#d49a85',
    kind: 'sovereign',
    emblem: 'ET',
  },
  kongo: {
    id: 'kongo',
    name: 'Kongo Confederacies',
    shortName: 'Kongo',
    color: '#705879',
    accent: '#b7a0c1',
    kind: 'sovereign',
    emblem: 'KO',
  },
  zulu: {
    id: 'zulu',
    name: 'Zulu Kingdom',
    shortName: 'Zulu',
    color: '#317266',
    accent: '#85b3a3',
    kind: 'sovereign',
    emblem: 'ZK',
  },
  sikh: {
    id: 'sikh',
    name: 'Sikh Empire',
    shortName: 'Sikh Empire',
    color: '#b27930',
    accent: '#ebbe68',
    kind: 'sovereign',
    emblem: 'SE',
  },
  maratha: {
    id: 'maratha',
    name: 'Maratha Confederacy',
    shortName: 'Maratha',
    color: '#a24f3d',
    accent: '#dd9980',
    kind: 'sovereign',
    emblem: 'MR',
  },
  burma: {
    id: 'burma',
    name: 'Konbaung Dynasty',
    shortName: 'Konbaung',
    color: '#7d5364',
    accent: '#c69aaa',
    kind: 'sovereign',
    emblem: 'KB',
  },
  qing: {
    id: 'qing',
    name: 'Great Qing',
    shortName: 'Qing',
    color: '#3d7562',
    accent: '#8ab8a0',
    kind: 'sovereign',
    emblem: 'QG',
  },
  spain: {
    id: 'spain',
    name: 'Kingdom of Spain',
    shortName: 'Spain',
    color: '#b18a3c',
    accent: '#e4cb84',
    kind: 'imperial',
    emblem: 'ES',
  },
  russia: {
    id: 'russia',
    name: 'Russian Empire',
    shortName: 'Russia',
    color: '#65806e',
    accent: '#b9cebe',
    kind: 'imperial',
    emblem: 'RU',
  },
  prussia: {
    id: 'prussia',
    name: 'Kingdom of Prussia',
    shortName: 'Prussia',
    color: '#465c70',
    accent: '#a9bdcd',
    kind: 'imperial',
    emblem: 'PR',
  },
  austria: {
    id: 'austria',
    name: 'Austrian Empire',
    shortName: 'Austria',
    color: '#8e6d67',
    accent: '#d2b4ad',
    kind: 'imperial',
    emblem: 'AT',
  },
  ottoman: {
    id: 'ottoman',
    name: 'Ottoman Empire',
    shortName: 'Ottomans',
    color: '#7d4d54',
    accent: '#d09a9d',
    kind: 'imperial',
    emblem: 'OT',
  },
  morocco: {
    id: 'morocco',
    name: 'Sultanate of Morocco',
    shortName: 'Morocco',
    color: '#8f5f42',
    accent: '#d8ab7d',
    kind: 'sovereign',
    emblem: 'MA',
  },
  algeria: {
    id: 'algeria',
    name: 'Emirate of Abdelkader',
    shortName: 'Algeria',
    color: '#547466',
    accent: '#a6c0aa',
    kind: 'sovereign',
    emblem: 'DZ',
  },
  egypt: {
    id: 'egypt',
    name: 'Khedivate of Egypt',
    shortName: 'Egypt',
    color: '#9b7650',
    accent: '#ddbd88',
    kind: 'sovereign',
    emblem: 'EG',
  },
  dahomey: {
    id: 'dahomey',
    name: 'Kingdom of Dahomey',
    shortName: 'Dahomey',
    color: '#7e554d',
    accent: '#c69a87',
    kind: 'sovereign',
    emblem: 'DH',
  },
  merina: {
    id: 'merina',
    name: 'Merina Kingdom',
    shortName: 'Merina',
    color: '#725d7f',
    accent: '#baa4c8',
    kind: 'sovereign',
    emblem: 'MK',
  },
  argentina: {
    id: 'argentina',
    name: 'Argentine Confederation',
    shortName: 'Argentina',
    color: '#6690a0',
    accent: '#b3d1d8',
    kind: 'sovereign',
    emblem: 'AR',
  },
  chile: {
    id: 'chile',
    name: 'Republic of Chile',
    shortName: 'Chile',
    color: '#5d6f8d',
    accent: '#abb8ce',
    kind: 'sovereign',
    emblem: 'CL',
  },
  peruBolivia: {
    id: 'peruBolivia',
    name: 'Peru–Bolivian Confederation',
    shortName: 'Peru–Bolivia',
    color: '#8b6750',
    accent: '#ceb197',
    kind: 'sovereign',
    emblem: 'PB',
  },
  qajar: {
    id: 'qajar',
    name: 'Qajar Iran',
    shortName: 'Qajar Iran',
    color: '#6f596f',
    accent: '#bba2b9',
    kind: 'sovereign',
    emblem: 'IR',
  },
  afghanistan: {
    id: 'afghanistan',
    name: 'Emirate of Afghanistan',
    shortName: 'Afghanistan',
    color: '#78664b',
    accent: '#c6b286',
    kind: 'sovereign',
    emblem: 'AF',
  },
  japan: {
    id: 'japan',
    name: 'Tokugawa Shogunate',
    shortName: 'Japan',
    color: '#825f68',
    accent: '#c9a8af',
    kind: 'sovereign',
    emblem: 'JP',
  },
  siam: {
    id: 'siam',
    name: 'Kingdom of Siam',
    shortName: 'Siam',
    color: '#8d6846',
    accent: '#d2ad75',
    kind: 'sovereign',
    emblem: 'SI',
  },
  vietnam: {
    id: 'vietnam',
    name: 'Nguyễn Đại Nam',
    shortName: 'Đại Nam',
    color: '#586f58',
    accent: '#a9bea1',
    kind: 'sovereign',
    emblem: 'VN',
  },
}

export const regions: Region[] = [
  {
    id: 'pacific-northwest',
    name: 'Pacific Northwest',
    theater: 'North America',
    path: 'M62 94 L126 65 L165 91 L148 148 L91 170 L58 137 Z',
    label: [108, 116],
    owner: 'coastSalish',
    people: 'Coast Salish & Chinook peoples',
    economy: 'Maritime exchange',
    good: 'Timber',
    doctrine: 'River & forest defense',
    doctrineDetail: 'War parties exploit waterways, cedar forests, and short interior supply lines.',
    terrain: 'Temperate rainforest',
    population: 0.8,
    prosperity: 46,
    resistance: 72,
    relation: 18,
    garrison: 38,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'northern-plains',
    name: 'Northern Plains',
    theater: 'North America',
    path: 'M126 65 L230 72 L251 130 L225 191 L148 148 L165 91 Z',
    label: [193, 121],
    owner: 'lakota',
    people: 'Lakota, Dakota & Nakota nations',
    economy: 'Bison commons',
    good: 'Horses',
    doctrine: 'Mounted maneuver',
    doctrineDetail: 'Highly mobile horse formations refuse fixed battle and strike exposed supply trains.',
    terrain: 'Open prairie',
    population: 0.6,
    prosperity: 52,
    resistance: 88,
    relation: -8,
    garrison: 62,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'great-lakes',
    name: 'Great Lakes',
    theater: 'North America',
    path: 'M230 72 L311 94 L337 146 L292 189 L225 191 L251 130 Z',
    label: [278, 127],
    owner: 'britain',
    people: 'Anishinaabe, Haudenosaunee & settler communities',
    economy: 'Lake trade',
    good: 'Furs',
    doctrine: 'Fortified waterways',
    doctrineDetail: 'Lake flotillas and treaty-aligned militias guard a thin chain of forts.',
    terrain: 'Lakes & woodland',
    population: 1.3,
    prosperity: 63,
    resistance: 31,
    relation: 65,
    garrison: 54,
    ports: 3,
    isCoastal: false,
  },
  {
    id: 'eastern-woodlands',
    name: 'Eastern Woodlands',
    theater: 'North America',
    path: 'M292 189 L337 146 L370 190 L350 215 L315 220 Z',
    label: [337, 188],
    owner: 'haudenosaunee',
    people: 'Haudenosaunee & Algonquian nations',
    economy: 'Mixed agriculture',
    good: 'Maize',
    doctrine: 'Woodland skirmishing',
    doctrineDetail: 'Decentralized companies use concealment, marksmanship, and prepared withdrawal routes.',
    terrain: 'Dense woodland',
    population: 1.9,
    prosperity: 59,
    resistance: 81,
    relation: 24,
    garrison: 58,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'american-republic',
    name: 'American Republic',
    theater: 'North America',
    path: 'M225 191 L292 189 L315 220 L350 215 L349 244 L283 250 Z',
    label: [289, 226],
    owner: 'unitedStates',
    people: 'United States frontier republic',
    economy: 'Canals, farms & manufactures',
    good: 'Machinery',
    doctrine: 'Volunteer columns',
    doctrineDetail: 'Regular infantry anchors a larger force of state volunteers, dragoons, and field artillery.',
    terrain: 'Wooded river valleys',
    population: 20.1,
    prosperity: 72,
    resistance: 24,
    relation: -12,
    garrison: 71,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'california',
    name: 'Alta California',
    theater: 'North America',
    path: 'M91 170 L148 148 L183 207 L159 266 L111 237 Z',
    label: [137, 208],
    owner: 'mexico',
    people: 'Californio & Indigenous communities',
    economy: 'Ranching frontier',
    good: 'Cattle',
    doctrine: 'Presidio cavalry',
    doctrineDetail: 'Light cavalry screen dispersed settlements and avoid long field campaigns.',
    terrain: 'Coastal valleys',
    population: 0.4,
    prosperity: 49,
    resistance: 43,
    relation: 8,
    garrison: 30,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'mexican-heartland',
    name: 'Mexican Heartland',
    theater: 'North America',
    path: 'M159 266 L183 207 L283 250 L299 291 L252 326 L190 309 Z',
    label: [231, 276],
    owner: 'mexico',
    people: 'Mexican Republic',
    economy: 'Silver & estates',
    good: 'Silver',
    doctrine: 'Defence in depth',
    doctrineDetail: 'Regular infantry anchors mountain passes while local cavalry contests the approaches.',
    terrain: 'High plateau',
    population: 7.2,
    prosperity: 58,
    resistance: 68,
    relation: -18,
    garrison: 68,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'new-granada',
    name: 'New Granada',
    theater: 'South America',
    path: 'M273 316 L335 314 L365 359 L323 393 L276 371 L252 342 Z',
    label: [312, 350],
    owner: 'granColombia',
    people: 'Gran Colombian Union',
    economy: 'Highland trade',
    good: 'Coffee',
    doctrine: 'Andean republican army',
    doctrineDetail: 'Veterans hold mountain roads and draw invaders into costly high-altitude marches.',
    terrain: 'Cloud forest',
    population: 2.8,
    prosperity: 61,
    resistance: 64,
    relation: 10,
    garrison: 55,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'amazon-basin',
    name: 'Amazon Basin',
    theater: 'South America',
    path: 'M323 393 L365 359 L435 376 L455 420 L420 457 L353 450 L316 425 Z',
    label: [389, 409],
    owner: 'tupinamba',
    people: 'Tupinambá & river nations',
    economy: 'River exchange',
    good: 'Medicinals',
    doctrine: 'Riverine evasion',
    doctrineDetail: 'Canoe flotillas control tributaries while settlements disperse beyond a marching army.',
    terrain: 'Rainforest rivers',
    population: 1.5,
    prosperity: 48,
    resistance: 95,
    relation: 4,
    garrison: 49,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'andean-highlands',
    name: 'Andean Highlands',
    theater: 'South America',
    path: 'M276 371 L323 393 L316 425 L337 494 L307 532 L275 467 L258 409 Z',
    label: [298, 448],
    owner: 'andean',
    people: 'Quechua & Aymara confederations',
    economy: 'Terraced agriculture',
    good: 'Quinine',
    doctrine: 'Mountain attrition',
    doctrineDetail: 'Community levies sever passes, deny forage, and weaponize altitude against outsiders.',
    terrain: 'High Andes',
    population: 3.4,
    prosperity: 55,
    resistance: 90,
    relation: -2,
    garrison: 61,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'brazilian-coast',
    name: 'Brazilian Coast',
    theater: 'South America',
    path: 'M435 376 L471 404 L462 471 L410 516 L337 494 L353 450 L420 457 L455 420 Z',
    label: [418, 451],
    owner: 'brazil',
    people: 'Empire of Brazil',
    economy: 'Plantation export',
    good: 'Coffee',
    doctrine: 'Coastal concentration',
    doctrineDetail: 'A centralized army moves between ports but struggles to sustain deep interior columns.',
    terrain: 'Atlantic uplands',
    population: 5.1,
    prosperity: 66,
    resistance: 57,
    relation: 28,
    garrison: 64,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'mapuche-country',
    name: 'Wallmapu',
    theater: 'South America',
    path: 'M307 532 L337 494 L410 516 L376 574 L332 565 Z',
    label: [354, 538],
    owner: 'mapuche',
    people: 'Mapuche Confederation',
    economy: 'Pastoral exchange',
    good: 'Horses',
    doctrine: 'Malón cavalry',
    doctrineDetail: 'Mounted columns gather rapidly, raid isolated posts, and dissolve across frontier rivers.',
    terrain: 'Steppe & woodland',
    population: 0.7,
    prosperity: 53,
    resistance: 93,
    relation: 12,
    garrison: 57,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'british-isles',
    name: 'British Isles',
    theater: 'Europe',
    path: 'M489 122 L502 92 L518 103 L513 128 L527 143 L510 164 L491 151 Z',
    label: [506, 132],
    owner: 'britain',
    people: 'British & Irish peoples',
    economy: 'Industrial finance',
    good: 'Machinery',
    doctrine: 'Expeditionary army',
    doctrineDetail: 'Professional line infantry depends on naval logistics and concentrated artillery.',
    terrain: 'Temperate islands',
    population: 25.4,
    prosperity: 86,
    resistance: 22,
    relation: 100,
    garrison: 82,
    ports: 6,
    isCoastal: true,
  },
  {
    id: 'france',
    name: 'France',
    theater: 'Europe',
    path: 'M512 164 L527 143 L559 146 L570 174 L546 199 L516 189 Z',
    label: [541, 173],
    owner: 'france',
    people: 'Kingdom of France',
    economy: 'Manufactures',
    good: 'Textiles',
    doctrine: 'Massed artillery',
    doctrineDetail: 'Large conscript formations seek decisive set-piece battles under heavy guns.',
    terrain: 'River lowlands',
    population: 33.5,
    prosperity: 82,
    resistance: 18,
    relation: -42,
    garrison: 84,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'iberia',
    name: 'Iberian Peninsula',
    theater: 'Europe',
    path: 'M489 198 L516 189 L546 199 L538 228 L501 239 L480 220 Z',
    label: [513, 215],
    owner: 'portugal',
    people: 'Portuguese & Spanish kingdoms',
    economy: 'Atlantic commerce',
    good: 'Wine',
    doctrine: 'Fortress network',
    doctrineDetail: 'Regional armies rely on defensible towns, local auxiliaries, and Atlantic resupply.',
    terrain: 'Dry uplands',
    population: 14.1,
    prosperity: 60,
    resistance: 35,
    relation: 14,
    garrison: 52,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'sokoto',
    name: 'Sokoto',
    theater: 'Africa',
    path: 'M486 288 L548 276 L590 305 L578 354 L521 356 L477 326 Z',
    label: [535, 319],
    owner: 'sokoto',
    people: 'Hausa & Fulani emirates',
    economy: 'Sahelian markets',
    good: 'Leather',
    doctrine: 'Emirate cavalry',
    doctrineDetail: 'Armored cavalry and fortified cities dominate the open Sahelian approaches.',
    terrain: 'Savanna & Sahel',
    population: 9.0,
    prosperity: 68,
    resistance: 85,
    relation: -6,
    garrison: 69,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'gold-coast',
    name: 'Gold Coast',
    theater: 'Africa',
    path: 'M477 326 L521 356 L535 389 L489 401 L459 366 Z',
    label: [493, 366],
    owner: 'ashanti',
    people: 'Ashanti Empire',
    economy: 'Gold & forest trade',
    good: 'Gold',
    doctrine: 'Forest envelopment',
    doctrineDetail: 'Layered wings move unseen through forest paths to surround rigid marching columns.',
    terrain: 'Tropical forest',
    population: 3.2,
    prosperity: 73,
    resistance: 91,
    relation: -32,
    garrison: 72,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'ethiopian-highlands',
    name: 'Ethiopian Highlands',
    theater: 'Africa',
    path: 'M590 305 L642 314 L668 359 L630 389 L578 354 Z',
    label: [621, 350],
    owner: 'ethiopia',
    people: 'Ethiopian Empire',
    economy: 'Highland agriculture',
    good: 'Coffee',
    doctrine: 'Highland host',
    doctrineDetail: 'Provincial hosts converge through known passes and overwhelm isolated detachments.',
    terrain: 'Escarpments',
    population: 5.4,
    prosperity: 62,
    resistance: 96,
    relation: 6,
    garrison: 75,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'kongo-basin',
    name: 'Kongo Basin',
    theater: 'Africa',
    path: 'M489 401 L535 389 L606 397 L619 449 L568 480 L510 461 Z',
    label: [553, 430],
    owner: 'kongo',
    people: 'Kongo & Luba polities',
    economy: 'River markets',
    good: 'Copper',
    doctrine: 'Dispersed resistance',
    doctrineDetail: 'Small formations exploit rivers and forest depth; control of a road never means control of the land.',
    terrain: 'Equatorial forest',
    population: 4.7,
    prosperity: 51,
    resistance: 94,
    relation: 2,
    garrison: 58,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'cape-colony',
    name: 'Cape Colony',
    theater: 'Africa',
    path: 'M510 461 L568 480 L621 458 L616 516 L572 553 L526 529 Z',
    label: [567, 507],
    owner: 'britain',
    people: 'Khoekhoe, Xhosa, settler & Cape communities',
    economy: 'Provisioning port',
    good: 'Wool',
    doctrine: 'Frontier columns',
    doctrineDetail: 'Mounted infantry can project along roads but remains tied to vulnerable wagon trains.',
    terrain: 'Veld & mountains',
    population: 0.3,
    prosperity: 64,
    resistance: 67,
    relation: 58,
    garrison: 57,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'zulu-kingdom',
    name: 'Zulu Kingdom',
    theater: 'Africa',
    path: 'M621 458 L651 430 L665 481 L645 527 L616 516 Z',
    label: [639, 484],
    owner: 'zulu',
    people: 'Zulu Kingdom',
    economy: 'Cattle & tribute',
    good: 'Cattle',
    doctrine: 'Horns of the buffalo',
    doctrineDetail: 'Disciplined regiments fix the enemy center while fast wings complete an encirclement.',
    terrain: 'Rolling grassland',
    population: 0.4,
    prosperity: 57,
    resistance: 98,
    relation: -15,
    garrison: 78,
    ports: 0,
    isCoastal: true,
  },
  {
    id: 'punjab',
    name: 'Punjab',
    theater: 'India',
    path: 'M720 273 L758 247 L797 263 L799 300 L754 315 L718 301 Z',
    label: [758, 281],
    owner: 'sikh',
    people: 'Sikh Empire',
    economy: 'Irrigated agriculture',
    good: 'Cotton',
    doctrine: 'Khalsa combined arms',
    doctrineDetail: 'Drilled infantry, mobile guns, and cavalry operate as an integrated field army.',
    terrain: 'Five rivers plain',
    population: 12.0,
    prosperity: 76,
    resistance: 84,
    relation: -21,
    garrison: 86,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'bengal',
    name: 'Bengal Presidency',
    theater: 'India',
    path: 'M799 300 L842 296 L861 333 L832 369 L791 350 L771 318 Z',
    label: [819, 329],
    owner: 'britain',
    people: 'Bengali communities under Company rule',
    economy: 'Textiles & revenue',
    good: 'Textiles',
    doctrine: 'Sepoy field army',
    doctrineDetail: 'Locally recruited infantry and European officers defend river magazines and arsenals.',
    terrain: 'River delta',
    population: 40.0,
    prosperity: 71,
    resistance: 49,
    relation: 48,
    garrison: 70,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'deccan',
    name: 'Deccan Confederacy',
    theater: 'India',
    path: 'M718 301 L754 315 L791 350 L778 415 L743 450 L715 399 L701 342 Z',
    label: [748, 367],
    owner: 'maratha',
    people: 'Maratha Confederacy',
    economy: 'Cotton & inland tolls',
    good: 'Cotton',
    doctrine: 'Mobile campaigning',
    doctrineDetail: 'Fast cavalry threatens communications while hill forts absorb time and manpower.',
    terrain: 'Plateau & hill forts',
    population: 18.0,
    prosperity: 67,
    resistance: 89,
    relation: -35,
    garrison: 74,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'konbaung-burma',
    name: 'Konbaung Burma',
    theater: 'Southeast Asia',
    path: 'M842 296 L882 305 L898 356 L875 414 L841 383 L832 369 L861 333 Z',
    label: [866, 351],
    owner: 'burma',
    people: 'Konbaung Dynasty',
    economy: 'Teak & rice',
    good: 'Teak',
    doctrine: 'Stockade warfare',
    doctrineDetail: 'Layered timber stockades, war elephants, and monsoon rivers halt linear advances.',
    terrain: 'Jungle river valleys',
    population: 4.0,
    prosperity: 60,
    resistance: 87,
    relation: -23,
    garrison: 67,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'south-china',
    name: 'South China',
    theater: 'China',
    path: 'M842 225 L917 221 L961 258 L948 311 L898 356 L882 305 L842 296 L819 264 Z',
    label: [900, 273],
    owner: 'qing',
    people: 'Great Qing',
    economy: 'Tea & porcelain',
    good: 'Tea',
    doctrine: 'Banner & Green Standard',
    doctrineDetail: 'Large regional forces draw on walled cities, river fleets, and deep local magazines.',
    terrain: 'River basins',
    population: 145.0,
    prosperity: 79,
    resistance: 82,
    relation: -27,
    garrison: 80,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'north-china',
    name: 'North China',
    theater: 'China',
    path: 'M797 159 L885 139 L960 163 L995 211 L961 258 L917 221 L842 225 L819 264 L789 221 Z',
    label: [890, 191],
    owner: 'qing',
    people: 'Great Qing',
    economy: 'Grain & administration',
    good: 'Porcelain',
    doctrine: 'Fortified strategic depth',
    doctrineDetail: 'Walled cities and immense reserves trade distance for time until relief armies assemble.',
    terrain: 'Northern plain',
    population: 165.0,
    prosperity: 75,
    resistance: 79,
    relation: -31,
    garrison: 85,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'java',
    name: 'Java',
    theater: 'Southeast Asia',
    path: 'M858 455 L914 461 L953 476 L938 494 L885 486 L849 469 Z',
    label: [903, 476],
    owner: 'netherlands',
    people: 'Javanese states under Company rule',
    economy: 'Cultivation system',
    good: 'Spices',
    doctrine: 'Fortified districts',
    doctrineDetail: 'Colonial garrisons hold roads and plantations but face persistent rural resistance.',
    terrain: 'Volcanic interior',
    population: 8.5,
    prosperity: 69,
    resistance: 71,
    relation: -12,
    garrison: 59,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'spain',
    name: 'Kingdom of Spain',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'spain',
    people: 'Spanish constitutional monarchy',
    economy: 'Agriculture & Atlantic ports',
    good: 'Wine',
    doctrine: 'Regional line armies',
    doctrineDetail: 'Line infantry and cavalry operate from a dense network of fortified towns.',
    terrain: 'Dry plateau & mountains',
    population: 12.2,
    prosperity: 57,
    resistance: 38,
    relation: 4,
    garrison: 61,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'prussia',
    name: 'Kingdom of Prussia',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'prussia',
    people: 'Kingdom of Prussia',
    economy: 'State manufactures',
    good: 'Arms',
    doctrine: 'Drilled line & reserve',
    doctrineDetail: 'Tightly drilled battalions combine fast mobilization with concentrated field artillery.',
    terrain: 'North European plain',
    population: 14.1,
    prosperity: 73,
    resistance: 28,
    relation: -8,
    garrison: 81,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'austrian-empire',
    name: 'Austrian Empire',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'austria',
    people: 'Habsburg crownlands',
    economy: 'Danubian agriculture',
    good: 'Iron',
    doctrine: 'Multinational field army',
    doctrineDetail: 'Large infantry formations and heavy guns defend river lines and Alpine approaches.',
    terrain: 'Danube basin & Alps',
    population: 34.0,
    prosperity: 70,
    resistance: 43,
    relation: 2,
    garrison: 80,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'russian-empire',
    name: 'Russian Empire',
    theater: 'Europe & Central Asia',
    path: '',
    label: [0, 0],
    owner: 'russia',
    people: 'Russian imperial crownlands',
    economy: 'Grain, timber & estates',
    good: 'Timber',
    doctrine: 'Strategic depth',
    doctrineDetail: 'Mass infantry, powerful batteries, and immense distances absorb an enemy advance.',
    terrain: 'Forest, steppe & taiga',
    population: 60.0,
    prosperity: 64,
    resistance: 48,
    relation: -12,
    garrison: 88,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'ottoman-heartlands',
    name: 'Ottoman Empire',
    theater: 'Eastern Mediterranean',
    path: '',
    label: [0, 0],
    owner: 'ottoman',
    people: 'Ottoman imperial provinces',
    economy: 'Caravan & port trade',
    good: 'Silk',
    doctrine: 'Reformed Mansure army',
    doctrineDetail: 'European-drilled infantry, field guns, and provincial cavalry guard the imperial roads.',
    terrain: 'Anatolian uplands',
    population: 26.0,
    prosperity: 66,
    resistance: 51,
    relation: 8,
    garrison: 76,
    ports: 6,
    isCoastal: true,
  },
  {
    id: 'morocco',
    name: 'Sultanate of Morocco',
    theater: 'North Africa',
    path: '',
    label: [0, 0],
    owner: 'morocco',
    people: 'Moroccan Sultanate',
    economy: 'Caravan & Atlantic trade',
    good: 'Leather',
    doctrine: 'Mahalla field host',
    doctrineDetail: 'Mounted contingents and musket infantry gather around the sultan’s mobile camp.',
    terrain: 'Atlas Mountains',
    population: 3.2,
    prosperity: 55,
    resistance: 82,
    relation: 6,
    garrison: 58,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'algerian-emirate',
    name: 'Emirate of Abdelkader',
    theater: 'North Africa',
    path: '',
    label: [0, 0],
    owner: 'algeria',
    people: 'Algerian emirate & tribal confederations',
    economy: 'Pastoral & caravan exchange',
    good: 'Horses',
    doctrine: 'Mobile resistance',
    doctrineDetail: 'Fast cavalry and riflemen disperse before columns, then strike exposed forts and convoys.',
    terrain: 'Tell Atlas & steppe',
    population: 2.6,
    prosperity: 49,
    resistance: 96,
    relation: -18,
    garrison: 72,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'egypt',
    name: 'Khedivate of Egypt',
    theater: 'North Africa',
    path: '',
    label: [0, 0],
    owner: 'egypt',
    people: 'Egypt under Muhammad Ali',
    economy: 'Cotton & Nile revenue',
    good: 'Cotton',
    doctrine: 'Nizam infantry & guns',
    doctrineDetail: 'Conscript battalions drilled in European fashion operate with a modern artillery arm.',
    terrain: 'Nile valley & desert',
    population: 4.5,
    prosperity: 72,
    resistance: 61,
    relation: -4,
    garrison: 82,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'dahomey',
    name: 'Kingdom of Dahomey',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'dahomey',
    people: 'Kingdom of Dahomey',
    economy: 'Royal markets',
    good: 'Palm oil',
    doctrine: 'Royal standing regiments',
    doctrineDetail: 'Disciplined women’s and men’s regiments combine close assault with imported firearms.',
    terrain: 'Coastal forest',
    population: 0.8,
    prosperity: 58,
    resistance: 91,
    relation: 3,
    garrison: 73,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'merina-kingdom',
    name: 'Merina Kingdom',
    theater: 'Indian Ocean',
    path: '',
    label: [0, 0],
    owner: 'merina',
    people: 'Merina Kingdom of Madagascar',
    economy: 'Highland rice & crafts',
    good: 'Rice',
    doctrine: 'Highland royal army',
    doctrineDetail: 'Musketeers and spear levies defend fortified highland roads and royal settlements.',
    terrain: 'Madagascar highlands',
    population: 1.1,
    prosperity: 54,
    resistance: 88,
    relation: 12,
    garrison: 63,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'argentine-confederation',
    name: 'Argentine Confederation',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'argentina',
    people: 'Argentine Confederation',
    economy: 'Cattle & river ports',
    good: 'Hides',
    doctrine: 'Gaucho cavalry',
    doctrineDetail: 'Mounted provincial forces dominate open country while infantry guards the river cities.',
    terrain: 'Pampas grassland',
    population: 1.2,
    prosperity: 60,
    resistance: 67,
    relation: 14,
    garrison: 57,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'chilean-republic',
    name: 'Republic of Chile',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'chile',
    people: 'Republic of Chile',
    economy: 'Pacific ports & mining',
    good: 'Copper',
    doctrine: 'Mountain republican army',
    doctrineDetail: 'Line infantry and cavalry use narrow valleys and Pacific ports for rapid concentration.',
    terrain: 'Coastal valleys & Andes',
    population: 1.0,
    prosperity: 63,
    resistance: 58,
    relation: 10,
    garrison: 62,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'peru-bolivia',
    name: 'Peru–Bolivia',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'peruBolivia',
    people: 'Peru–Bolivian Confederation',
    economy: 'Silver & highland markets',
    good: 'Silver',
    doctrine: 'Highland republican columns',
    doctrineDetail: 'Infantry and guns command the altiplano roads while cavalry screens the valleys.',
    terrain: 'Altiplano & desert coast',
    population: 4.5,
    prosperity: 62,
    resistance: 72,
    relation: 8,
    garrison: 68,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'qajar-iran',
    name: 'Qajar Iran',
    theater: 'Central Asia',
    path: '',
    label: [0, 0],
    owner: 'qajar',
    people: 'Qajar Iran',
    economy: 'Silk & caravan trade',
    good: 'Silk',
    doctrine: 'Tribal cavalry & sarbaz',
    doctrineDetail: 'Reformed infantry holds the towns while cavalry contests long desert approaches.',
    terrain: 'Iranian plateau',
    population: 7.0,
    prosperity: 59,
    resistance: 78,
    relation: 5,
    garrison: 66,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'afghan-emirate',
    name: 'Afghan Emirate',
    theater: 'Central Asia',
    path: '',
    label: [0, 0],
    owner: 'afghanistan',
    people: 'Afghan emirate & tribal confederations',
    economy: 'Caravan tolls',
    good: 'Horses',
    doctrine: 'Jezail marksmen',
    doctrineDetail: 'Long-range jezail fire and mountain ambushes punish armies tied to narrow passes.',
    terrain: 'Mountain passes',
    population: 4.0,
    prosperity: 48,
    resistance: 97,
    relation: -11,
    garrison: 74,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'tokugawa-japan',
    name: 'Tokugawa Japan',
    theater: 'East Asia',
    path: '',
    label: [0, 0],
    owner: 'japan',
    people: 'Tokugawa Shogunate',
    economy: 'Rice, crafts & coastal trade',
    good: 'Lacquerware',
    doctrine: 'Domain armies',
    doctrineDetail: 'Samurai-led formations combine matchlock ashigaru, spearmen, bows, and coastal batteries.',
    terrain: 'Mountainous islands',
    population: 32.0,
    prosperity: 74,
    resistance: 85,
    relation: -7,
    garrison: 79,
    ports: 6,
    isCoastal: true,
  },
  {
    id: 'siam',
    name: 'Kingdom of Siam',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'siam',
    people: 'Kingdom of Siam',
    economy: 'Rice & entrepôt trade',
    good: 'Rice',
    doctrine: 'River-centered royal army',
    doctrineDetail: 'Musketeers, elephant corps, and fortified river towns anchor the kingdom’s defense.',
    terrain: 'River plain & jungle',
    population: 4.0,
    prosperity: 65,
    resistance: 80,
    relation: 16,
    garrison: 65,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'dai-nam',
    name: 'Đại Nam',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'vietnam',
    people: 'Nguyễn Đại Nam',
    economy: 'Rice & court workshops',
    good: 'Rice',
    doctrine: 'Citadel & river defense',
    doctrineDetail: 'Matchlock infantry and artillery defend Vauban-style citadels and narrow river corridors.',
    terrain: 'Coastal deltas & highlands',
    population: 8.0,
    prosperity: 62,
    resistance: 86,
    relation: 4,
    garrison: 72,
    ports: 4,
    isCoastal: true,
  },
]

export const initialEvents: CampaignEvent[] = [
  {
    id: 1,
    type: 'world',
    title: 'The race for influence accelerates',
    body: 'French missions have arrived at the court of the Ashanti Asantehene.',
    turn: 1,
  },
  {
    id: 2,
    type: 'trade',
    title: 'Tea auctions reach a new high',
    body: 'Merchants urge the cabinet to secure a durable agreement with Great Qing.',
    turn: 1,
  },
  {
    id: 3,
    type: 'diplomacy',
    title: 'Envoys from the Great Lakes',
    body: 'Anishinaabe leaders request that old treaty boundaries be reaffirmed.',
    turn: 1,
  },
]

export const tradeRoutes = [
  { id: 'atlantic-north', d: 'M 505 145 Q 410 55 300 135', tone: 'player' },
  { id: 'atlantic-south', d: 'M 510 170 Q 420 285 490 364', tone: 'player' },
  { id: 'cape-india', d: 'M 568 507 Q 680 565 819 329', tone: 'player' },
  { id: 'china-route', d: 'M 819 329 Q 875 380 930 287', tone: 'contested' },
  { id: 'france-west-africa', d: 'M 541 173 Q 445 245 493 366', tone: 'rival' },
]
