import type { CampaignEvent, Faction, Region } from './types'

export const factions: Record<string, Faction> = {
  unitedStates: {
    id: 'unitedStates',
    name: 'United States',
    shortName: 'United States',
    color: '#496b82',
    accent: '#b8d1df',
    kind: 'imperial',
    emblem: 'US',
  },
  britain: {
    id: 'britain',
    name: 'British Empire',
    shortName: 'Britain',
    color: '#a8413e',
    accent: '#e8b9ae',
    kind: 'imperial',
    emblem: 'BR',
  },
  france: {
    id: 'france',
    name: 'Kingdom of France',
    shortName: 'France',
    color: '#536f91',
    accent: '#bfd1de',
    kind: 'imperial',
    emblem: 'FR',
  },
  portugal: {
    id: 'portugal',
    name: 'Portuguese Crown',
    shortName: 'Portugal',
    color: '#6d7655',
    accent: '#ced3a7',
    kind: 'imperial',
    emblem: 'PT',
  },
  netherlands: {
    id: 'netherlands',
    name: 'Dutch Trading Company',
    shortName: 'Dutch Company',
    color: '#b66a3c',
    accent: '#f0bd83',
    kind: 'commercial',
    emblem: 'VOC',
  },
  haudenosaunee: {
    id: 'haudenosaunee',
    name: 'Haudenosaunee Confederacy',
    shortName: 'Haudenosaunee',
    color: '#47766d',
    accent: '#9ec1b2',
    kind: 'sovereign',
    emblem: 'HC',
  },
  coastSalish: {
    id: 'coastSalish',
    name: 'Coast Salish Nations',
    shortName: 'Coast Salish',
    color: '#486f79',
    accent: '#9fc4ca',
    kind: 'sovereign',
    emblem: 'CS',
  },
  lakota: {
    id: 'lakota',
    name: 'Lakota Oyate',
    shortName: 'Lakota',
    color: '#8f5c46',
    accent: '#d8ad82',
    kind: 'sovereign',
    emblem: 'LO',
  },
  mexico: {
    id: 'mexico',
    name: 'Mexican Republic',
    shortName: 'Mexico',
    color: '#56785e',
    accent: '#a8c09e',
    kind: 'sovereign',
    emblem: 'MX',
  },
  granColombia: {
    id: 'granColombia',
    name: 'Gran Colombian Union',
    shortName: 'Gran Colombia',
    color: '#a8863f',
    accent: '#dec789',
    kind: 'sovereign',
    emblem: 'GC',
  },
  tupinamba: {
    id: 'tupinamba',
    name: 'Amazonian River Confederacies',
    shortName: 'River Nations',
    color: '#3f7663',
    accent: '#83b19a',
    kind: 'sovereign',
    emblem: 'AR',
  },
  brazil: {
    id: 'brazil',
    name: 'Empire of Brazil',
    shortName: 'Brazil',
    color: '#79813d',
    accent: '#d0cd80',
    kind: 'sovereign',
    emblem: 'BZ',
  },
  andean: {
    id: 'andean',
    name: 'Andean Confederation',
    shortName: 'Andean Confederation',
    color: '#806455',
    accent: '#c8ad94',
    kind: 'sovereign',
    emblem: 'AC',
  },
  mapuche: {
    id: 'mapuche',
    name: 'Mapuche Confederation',
    shortName: 'Mapuche',
    color: '#4c6d83',
    accent: '#9eb6c7',
    kind: 'sovereign',
    emblem: 'MC',
  },
  sokoto: {
    id: 'sokoto',
    name: 'Sokoto Caliphate',
    shortName: 'Sokoto',
    color: '#967641',
    accent: '#d9bd7f',
    kind: 'sovereign',
    emblem: 'SK',
  },
  ashanti: {
    id: 'ashanti',
    name: 'Ashanti Empire',
    shortName: 'Ashanti',
    color: '#a36c2b',
    accent: '#e1b65d',
    kind: 'sovereign',
    emblem: 'AS',
  },
  ethiopia: {
    id: 'ethiopia',
    name: 'Ethiopian Empire',
    shortName: 'Ethiopia',
    color: '#8d4f48',
    accent: '#d49a85',
    kind: 'sovereign',
    emblem: 'ET',
  },
  kongo: {
    id: 'kongo',
    name: 'Kongo Confederacies',
    shortName: 'Kongo',
    color: '#705879',
    accent: '#b7a0c1',
    kind: 'sovereign',
    emblem: 'KO',
  },
  zulu: {
    id: 'zulu',
    name: 'Zulu Kingdom',
    shortName: 'Zulu',
    color: '#317266',
    accent: '#85b3a3',
    kind: 'sovereign',
    emblem: 'ZK',
  },
  sikh: {
    id: 'sikh',
    name: 'Sikh Empire',
    shortName: 'Sikh Empire',
    color: '#b27930',
    accent: '#ebbe68',
    kind: 'sovereign',
    emblem: 'SE',
  },
  maratha: {
    id: 'maratha',
    name: 'Maratha Confederacy',
    shortName: 'Maratha',
    color: '#a24f3d',
    accent: '#dd9980',
    kind: 'sovereign',
    emblem: 'MR',
  },
  burma: {
    id: 'burma',
    name: 'Konbaung Dynasty',
    shortName: 'Konbaung',
    color: '#7d5364',
    accent: '#c69aaa',
    kind: 'sovereign',
    emblem: 'KB',
  },
  qing: {
    id: 'qing',
    name: 'Great Qing',
    shortName: 'Qing',
    color: '#3d7562',
    accent: '#8ab8a0',
    kind: 'sovereign',
    emblem: 'QG',
  },
  spain: {
    id: 'spain',
    name: 'Kingdom of Spain',
    shortName: 'Spain',
    color: '#b18a3c',
    accent: '#e4cb84',
    kind: 'imperial',
    emblem: 'ES',
  },
  russia: {
    id: 'russia',
    name: 'Russian Empire',
    shortName: 'Russia',
    color: '#65806e',
    accent: '#b9cebe',
    kind: 'imperial',
    emblem: 'RU',
  },
  prussia: {
    id: 'prussia',
    name: 'Kingdom of Prussia',
    shortName: 'Prussia',
    color: '#465c70',
    accent: '#a9bdcd',
    kind: 'imperial',
    emblem: 'PR',
  },
  austria: {
    id: 'austria',
    name: 'Austrian Empire',
    shortName: 'Austria',
    color: '#8e6d67',
    accent: '#d2b4ad',
    kind: 'imperial',
    emblem: 'AT',
  },
  ottoman: {
    id: 'ottoman',
    name: 'Ottoman Empire',
    shortName: 'Ottomans',
    color: '#7d4d54',
    accent: '#d09a9d',
    kind: 'imperial',
    emblem: 'OT',
  },
  morocco: {
    id: 'morocco',
    name: 'Sultanate of Morocco',
    shortName: 'Morocco',
    color: '#8f5f42',
    accent: '#d8ab7d',
    kind: 'sovereign',
    emblem: 'MA',
  },
  algeria: {
    id: 'algeria',
    name: 'Emirate of Abdelkader',
    shortName: 'Algeria',
    color: '#547466',
    accent: '#a6c0aa',
    kind: 'sovereign',
    emblem: 'DZ',
  },
  egypt: {
    id: 'egypt',
    name: 'Khedivate of Egypt',
    shortName: 'Egypt',
    color: '#9b7650',
    accent: '#ddbd88',
    kind: 'sovereign',
    emblem: 'EG',
  },
  dahomey: {
    id: 'dahomey',
    name: 'Kingdom of Dahomey',
    shortName: 'Dahomey',
    color: '#7e554d',
    accent: '#c69a87',
    kind: 'sovereign',
    emblem: 'DH',
  },
  merina: {
    id: 'merina',
    name: 'Merina Kingdom',
    shortName: 'Merina',
    color: '#725d7f',
    accent: '#baa4c8',
    kind: 'sovereign',
    emblem: 'MK',
  },
  argentina: {
    id: 'argentina',
    name: 'Argentine Confederation',
    shortName: 'Argentina',
    color: '#6690a0',
    accent: '#b3d1d8',
    kind: 'sovereign',
    emblem: 'AR',
  },
  chile: {
    id: 'chile',
    name: 'Republic of Chile',
    shortName: 'Chile',
    color: '#5d6f8d',
    accent: '#abb8ce',
    kind: 'sovereign',
    emblem: 'CL',
  },
  peruBolivia: {
    id: 'peruBolivia',
    name: 'Peru–Bolivian Confederation',
    shortName: 'Peru–Bolivia',
    color: '#8b6750',
    accent: '#ceb197',
    kind: 'sovereign',
    emblem: 'PB',
  },
  qajar: {
    id: 'qajar',
    name: 'Qajar Iran',
    shortName: 'Qajar Iran',
    color: '#6f596f',
    accent: '#bba2b9',
    kind: 'sovereign',
    emblem: 'IR',
  },
  afghanistan: {
    id: 'afghanistan',
    name: 'Emirate of Afghanistan',
    shortName: 'Afghanistan',
    color: '#78664b',
    accent: '#c6b286',
    kind: 'sovereign',
    emblem: 'AF',
  },
  japan: {
    id: 'japan',
    name: 'Tokugawa Shogunate',
    shortName: 'Japan',
    color: '#825f68',
    accent: '#c9a8af',
    kind: 'sovereign',
    emblem: 'JP',
  },
  siam: {
    id: 'siam',
    name: 'Kingdom of Siam',
    shortName: 'Siam',
    color: '#8d6846',
    accent: '#d2ad75',
    kind: 'sovereign',
    emblem: 'SI',
  },
  vietnam: {
    id: 'vietnam',
    name: 'Nguyễn Đại Nam',
    shortName: 'Đại Nam',
    color: '#586f58',
    accent: '#a9bea1',
    kind: 'sovereign',
    emblem: 'VN',
  },
}

export const regions: Region[] = [
  {
    id: 'canadian-maritimes',
    name: 'Canadian Maritimes',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Mi\'kmaq, Acadian & British settler communities',
    economy: 'Cod & timber trade',
    good: 'Timber',
    rawMaterial: 'Timber',
    marketDemand: 55,
    isMetropolis: false,
    doctrine: 'Naval garrison',
    doctrineDetail: 'Frigates and coastal forts secure the Gulf approaches.',
    terrain: 'Fogbound coasts',
    population: 0.5,
    prosperity: 62,
    resistance: 44,
    relation: 55,
    garrison: 58,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'great-lakes',
    name: 'Upper Canada & Great Lakes',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Anishinaabe, Haudenosaunee & British settler communities',
    economy: 'Lake trade & furs',
    good: 'Furs',
    rawMaterial: 'Furs',
    marketDemand: 48,
    isMetropolis: false,
    doctrine: 'Fortified waterways',
    doctrineDetail: 'Lake flotillas and treaty militias guard a chain of forts.',
    terrain: 'Lakes & woodland',
    population: 1.4,
    prosperity: 64,
    resistance: 38,
    relation: 50,
    garrison: 56,
    ports: 3,
    isCoastal: false,
  },
  {
    id: 'atlantic-seaboard',
    name: 'Atlantic Seaboard',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'unitedStates',
    people: 'United States republic',
    economy: 'Ports, farms & early mills',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 72,
    isMetropolis: true,
    doctrine: 'Volunteer columns',
    doctrineDetail: 'Regular infantry anchors volunteers, dragoons, and field guns.',
    terrain: 'Wooded coast',
    population: 12.0,
    prosperity: 78,
    resistance: 22,
    relation: 100,
    garrison: 78,
    ports: 6,
    isCoastal: true,
  },
  {
    id: 'ohio-valley',
    name: 'Ohio Valley',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'unitedStates',
    people: 'Settler republic & displaced nations',
    economy: 'Grain & river trade',
    good: 'Maize',
    rawMaterial: 'Maize',
    marketDemand: 68,
    isMetropolis: false,
    doctrine: 'Frontier militia',
    doctrineDetail: 'Militia and regulars push river roads into contested interior.',
    terrain: 'River valleys',
    population: 3.2,
    prosperity: 70,
    resistance: 45,
    relation: 100,
    garrison: 64,
    ports: 1,
    isCoastal: false,
  },
  {
    id: 'mississippi-basin',
    name: 'Mississippi Basin',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'unitedStates',
    people: 'United States & river nations',
    economy: 'Cotton & river commerce',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 74,
    isMetropolis: false,
    doctrine: 'Riverine logistics',
    doctrineDetail: 'Steamboats and depots feed columns into the deep South and West.',
    terrain: 'Alluvial plain',
    population: 4.8,
    prosperity: 73,
    resistance: 40,
    relation: 100,
    garrison: 66,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'northern-plains',
    name: 'Northern Plains',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'lakota',
    people: 'Lakota, Dakota & Nakota nations',
    economy: 'Bison commons',
    good: 'Hides',
    rawMaterial: 'Hides',
    marketDemand: 35,
    isMetropolis: false,
    doctrine: 'Mounted maneuver',
    doctrineDetail: 'Horse nations refuse fixed battle and strike supply trains.',
    terrain: 'Open prairie',
    population: 0.6,
    prosperity: 52,
    resistance: 90,
    relation: -8,
    garrison: 68,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'southern-plains',
    name: 'Southern Plains',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'lakota',
    people: 'Comanche, Kiowa & allied nations',
    economy: 'Horse & hide exchange',
    good: 'Horses',
    rawMaterial: 'Horses',
    marketDemand: 32,
    isMetropolis: false,
    doctrine: 'Mounted raiding',
    doctrineDetail: 'Fast horse columns dominate the open southern plains.',
    terrain: 'Dry plains',
    population: 0.4,
    prosperity: 50,
    resistance: 92,
    relation: -12,
    garrison: 70,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'pacific-northwest',
    name: 'Pacific Northwest',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'coastSalish',
    people: 'Coast Salish & Chinook peoples',
    economy: 'Maritime exchange',
    good: 'Timber',
    rawMaterial: 'Timber',
    marketDemand: 40,
    isMetropolis: false,
    doctrine: 'River & forest defense',
    doctrineDetail: 'War parties use waterways and cedar forests.',
    terrain: 'Temperate rainforest',
    population: 0.8,
    prosperity: 46,
    resistance: 74,
    relation: 18,
    garrison: 42,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'california',
    name: 'Alta California',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'mexico',
    people: 'Californio & Indigenous communities',
    economy: 'Ranching frontier',
    good: 'Cattle',
    rawMaterial: 'Cattle',
    marketDemand: 42,
    isMetropolis: false,
    doctrine: 'Presidio cavalry',
    doctrineDetail: 'Light cavalry screens dispersed settlements.',
    terrain: 'Coastal valleys',
    population: 0.4,
    prosperity: 49,
    resistance: 48,
    relation: 8,
    garrison: 32,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'mexican-heartland',
    name: 'Mexican Heartland',
    theater: 'North America',
    path: '',
    label: [0, 0],
    owner: 'mexico',
    people: 'Mexican Republic',
    economy: 'Silver & estates',
    good: 'Silver',
    rawMaterial: 'Silver',
    marketDemand: 58,
    isMetropolis: false,
    doctrine: 'Defence in depth',
    doctrineDetail: 'Regulars hold mountain passes; cavalry contests approaches.',
    terrain: 'High plateau',
    population: 7.2,
    prosperity: 58,
    resistance: 70,
    relation: -18,
    garrison: 70,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'cuba',
    name: 'Cuba',
    theater: 'Caribbean',
    path: '',
    label: [0, 0],
    owner: 'spain',
    people: 'Spanish Cuba',
    economy: 'Sugar plantation colony',
    good: 'Sugar',
    rawMaterial: 'Sugar',
    marketDemand: 80,
    isMetropolis: false,
    doctrine: 'Colonial garrison',
    doctrineDetail: 'Coastal forts and militia secure the sugar ports.',
    terrain: 'Tropical island',
    population: 1.0,
    prosperity: 71,
    resistance: 52,
    relation: 20,
    garrison: 55,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'jamaica',
    name: 'Jamaica',
    theater: 'Caribbean',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'British Jamaica',
    economy: 'Sugar & naval station',
    good: 'Sugar',
    rawMaterial: 'Sugar',
    marketDemand: 78,
    isMetropolis: false,
    doctrine: 'Naval station',
    doctrineDetail: 'The West India squadron and island militia hold Kingston.',
    terrain: 'Tropical island',
    population: 0.4,
    prosperity: 68,
    resistance: 55,
    relation: 60,
    garrison: 52,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'guianas',
    name: 'The Guianas',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'netherlands',
    people: 'Dutch, British & French Guiana',
    economy: 'Plantation coast',
    good: 'Sugar',
    rawMaterial: 'Sugar',
    marketDemand: 70,
    isMetropolis: false,
    doctrine: 'Coastal factories',
    doctrineDetail: 'Company forts cling to the rivers behind mangrove coasts.',
    terrain: 'Coastal rainforest',
    population: 0.2,
    prosperity: 55,
    resistance: 62,
    relation: 10,
    garrison: 40,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'new-granada',
    name: 'New Granada',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'granColombia',
    people: 'Gran Colombian Union',
    economy: 'Highland trade',
    good: 'Coffee',
    rawMaterial: 'Coffee',
    marketDemand: 55,
    isMetropolis: false,
    doctrine: 'Andean republican army',
    doctrineDetail: 'Veterans hold mountain roads against costly marches.',
    terrain: 'Cloud forest',
    population: 2.8,
    prosperity: 61,
    resistance: 64,
    relation: 10,
    garrison: 55,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'amazon-basin',
    name: 'Amazon Basin',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'tupinamba',
    people: 'Tupinambá & river nations',
    economy: 'River exchange',
    good: 'Rubber',
    rawMaterial: 'Rubber',
    marketDemand: 28,
    isMetropolis: false,
    doctrine: 'Riverine evasion',
    doctrineDetail: 'Canoe flotillas control tributaries beyond marching armies.',
    terrain: 'Rainforest rivers',
    population: 1.5,
    prosperity: 48,
    resistance: 95,
    relation: 4,
    garrison: 49,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'brazilian-coast',
    name: 'Brazilian Coast',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'brazil',
    people: 'Empire of Brazil',
    economy: 'Plantation export',
    good: 'Coffee',
    rawMaterial: 'Coffee',
    marketDemand: 66,
    isMetropolis: false,
    doctrine: 'Coastal concentration',
    doctrineDetail: 'A centralized army moves between ports, not deep interior.',
    terrain: 'Atlantic uplands',
    population: 5.1,
    prosperity: 66,
    resistance: 57,
    relation: 28,
    garrison: 64,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'andean-highlands',
    name: 'Andean Highlands',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'andean',
    people: 'Quechua & Aymara confederations',
    economy: 'Terraced agriculture',
    good: 'Quinine',
    rawMaterial: 'Quinine',
    marketDemand: 30,
    isMetropolis: false,
    doctrine: 'Mountain attrition',
    doctrineDetail: 'Levies sever passes and weaponize altitude.',
    terrain: 'High Andes',
    population: 3.4,
    prosperity: 55,
    resistance: 90,
    relation: -2,
    garrison: 61,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'peru-bolivia',
    name: 'Peru–Bolivia',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'peruBolivia',
    people: 'Peru–Bolivian Confederation',
    economy: 'Silver & highland markets',
    good: 'Silver',
    rawMaterial: 'Silver',
    marketDemand: 50,
    isMetropolis: false,
    doctrine: 'Highland defence',
    doctrineDetail: 'Mountain armies contest the altiplano roads.',
    terrain: 'Altiplano',
    population: 2.5,
    prosperity: 56,
    resistance: 72,
    relation: 5,
    garrison: 58,
    ports: 1,
    isCoastal: false,
  },
  {
    id: 'chilean-republic',
    name: 'Chile',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'chile',
    people: 'Republic of Chile',
    economy: 'Pacific ports & mining',
    good: 'Copper',
    rawMaterial: 'Copper',
    marketDemand: 52,
    isMetropolis: false,
    doctrine: 'Coastal republic',
    doctrineDetail: 'Regulars hold the long Pacific littoral.',
    terrain: 'Coastal range',
    population: 1.2,
    prosperity: 60,
    resistance: 58,
    relation: 12,
    garrison: 54,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'argentine-confederation',
    name: 'Argentine Confederation',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'argentina',
    people: 'Argentine Confederation',
    economy: 'Cattle & river ports',
    good: 'Hides',
    rawMaterial: 'Hides',
    marketDemand: 54,
    isMetropolis: false,
    doctrine: 'Pampas cavalry',
    doctrineDetail: 'Mounted columns dominate the open pampas.',
    terrain: 'Pampas',
    population: 1.0,
    prosperity: 58,
    resistance: 60,
    relation: 8,
    garrison: 52,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'mapuche-country',
    name: 'Wallmapu',
    theater: 'South America',
    path: '',
    label: [0, 0],
    owner: 'mapuche',
    people: 'Mapuche Confederation',
    economy: 'Pastoral exchange',
    good: 'Horses',
    rawMaterial: 'Horses',
    marketDemand: 34,
    isMetropolis: false,
    doctrine: 'Malón cavalry',
    doctrineDetail: 'Mounted columns raid posts and dissolve across rivers.',
    terrain: 'Steppe & woodland',
    population: 0.7,
    prosperity: 53,
    resistance: 93,
    relation: 12,
    garrison: 57,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'british-isles',
    name: 'British Isles',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'British & Irish peoples',
    economy: 'Industrial workshops',
    good: 'Coal',
    rawMaterial: 'Coal',
    marketDemand: 40,
    isMetropolis: true,
    doctrine: 'Expeditionary army',
    doctrineDetail: 'Professional line infantry depends on naval logistics.',
    terrain: 'Temperate islands',
    population: 25.4,
    prosperity: 90,
    resistance: 18,
    relation: 100,
    garrison: 88,
    ports: 6,
    isCoastal: true,
  },
  {
    id: 'france',
    name: 'France',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'france',
    people: 'Kingdom of France',
    economy: 'Manufactures & arsenals',
    good: 'Iron',
    rawMaterial: 'Iron',
    marketDemand: 42,
    isMetropolis: true,
    doctrine: 'Massed artillery',
    doctrineDetail: 'Conscript formations seek set-piece battles under heavy guns.',
    terrain: 'River lowlands',
    population: 33.5,
    prosperity: 86,
    resistance: 16,
    relation: 100,
    garrison: 86,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'low-countries',
    name: 'Low Countries',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'netherlands',
    people: 'Dutch Republic & Belgium',
    economy: 'Colonial finance',
    good: 'Machinery',
    rawMaterial: 'Machinery',
    marketDemand: 45,
    isMetropolis: true,
    doctrine: 'Company armies',
    doctrineDetail: 'Trading companies fund colonial garrisons from Amsterdam.',
    terrain: 'Lowland coasts',
    population: 5.5,
    prosperity: 84,
    resistance: 20,
    relation: 100,
    garrison: 70,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'spain',
    name: 'Spain',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'spain',
    people: 'Kingdom of Spain',
    economy: 'Atlantic commerce',
    good: 'Wine',
    rawMaterial: 'Wine',
    marketDemand: 38,
    isMetropolis: true,
    doctrine: 'Regional line armies',
    doctrineDetail: 'Line infantry operate from fortified towns.',
    terrain: 'Dry plateau',
    population: 12.2,
    prosperity: 60,
    resistance: 35,
    relation: 100,
    garrison: 62,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'portugal',
    name: 'Portugal',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'portugal',
    people: 'Portuguese Crown',
    economy: 'Atlantic empire finance',
    good: 'Wine',
    rawMaterial: 'Wine',
    marketDemand: 36,
    isMetropolis: true,
    doctrine: 'Fortress network',
    doctrineDetail: 'Atlantic forts and local auxiliaries sustain overseas posts.',
    terrain: 'Atlantic coast',
    population: 3.5,
    prosperity: 62,
    resistance: 28,
    relation: 100,
    garrison: 58,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'prussia',
    name: 'Kingdom of Prussia',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'prussia',
    people: 'Kingdom of Prussia',
    economy: 'State manufactures',
    good: 'Arms',
    rawMaterial: 'Arms',
    marketDemand: 30,
    isMetropolis: true,
    doctrine: 'Drilled line & reserve',
    doctrineDetail: 'Drilled battalions mobilize with concentrated artillery.',
    terrain: 'North European plain',
    population: 14.1,
    prosperity: 73,
    resistance: 25,
    relation: 0,
    garrison: 72,
    ports: 2,
    isCoastal: false,
  },
  {
    id: 'austrian-empire',
    name: 'Austrian Empire',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'austria',
    people: 'Austrian Empire',
    economy: 'Danubian agriculture',
    good: 'Iron',
    rawMaterial: 'Iron',
    marketDemand: 28,
    isMetropolis: true,
    doctrine: 'Multi-national army',
    doctrineDetail: 'Imperial regiments hold the Danubian approaches.',
    terrain: 'Alpine & plain',
    population: 28.0,
    prosperity: 68,
    resistance: 30,
    relation: 0,
    garrison: 74,
    ports: 1,
    isCoastal: false,
  },
  {
    id: 'russian-empire',
    name: 'Russian Empire',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'russia',
    people: 'Russian Empire',
    economy: 'Grain, timber & estates',
    good: 'Timber',
    rawMaterial: 'Timber',
    marketDemand: 25,
    isMetropolis: true,
    doctrine: 'Imperial mass',
    doctrineDetail: 'Immense reserves trade distance for time.',
    terrain: 'Steppe & forest',
    population: 55.0,
    prosperity: 58,
    resistance: 40,
    relation: 0,
    garrison: 80,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'ottoman-heartlands',
    name: 'Ottoman Heartlands',
    theater: 'Europe',
    path: '',
    label: [0, 0],
    owner: 'ottoman',
    people: 'Ottoman Empire',
    economy: 'Caravan & port trade',
    good: 'Silk',
    rawMaterial: 'Silk',
    marketDemand: 40,
    isMetropolis: false,
    doctrine: 'Imperial janissary legacy',
    doctrineDetail: 'Provincial armies and forts guard the straits.',
    terrain: 'Anatolian plateau',
    population: 18.0,
    prosperity: 55,
    resistance: 55,
    relation: 0,
    garrison: 68,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'morocco',
    name: 'Morocco',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'morocco',
    people: 'Sultanate of Morocco',
    economy: 'Caravan & Atlantic trade',
    good: 'Leather',
    rawMaterial: 'Leather',
    marketDemand: 45,
    isMetropolis: false,
    doctrine: 'Sharifian host',
    doctrineDetail: 'Tribal cavalry and coastal batteries contest landings.',
    terrain: 'Atlas & coast',
    population: 3.0,
    prosperity: 54,
    resistance: 78,
    relation: 5,
    garrison: 60,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'algerian-emirate',
    name: 'Algeria',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'algeria',
    people: 'Emirate of Abdelkader',
    economy: 'Pastoral & caravan exchange',
    good: 'Hides',
    rawMaterial: 'Hides',
    marketDemand: 40,
    isMetropolis: false,
    doctrine: 'Desert & mountain war',
    doctrineDetail: 'Mobile resistance denies the coastal plain to invaders.',
    terrain: 'Tell & desert',
    population: 2.5,
    prosperity: 50,
    resistance: 88,
    relation: -20,
    garrison: 65,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'egypt',
    name: 'Egypt',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'egypt',
    people: 'Khedivate of Egypt',
    economy: 'Cotton & Nile revenue',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 62,
    isMetropolis: false,
    doctrine: 'Nile army',
    doctrineDetail: 'Modernizing battalions hold the Delta and Upper Nile.',
    terrain: 'Nile valley',
    population: 5.0,
    prosperity: 65,
    resistance: 60,
    relation: 10,
    garrison: 70,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'senegal',
    name: 'Senegal Coast',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'france',
    people: 'Wolof states & French comptoirs',
    economy: 'Gum & coastal trade',
    good: 'Gum arabic',
    rawMaterial: 'Gum arabic',
    marketDemand: 58,
    isMetropolis: false,
    doctrine: 'Coastal comptoir',
    doctrineDetail: 'Forts at Saint-Louis project limited river columns.',
    terrain: 'Sahel coast',
    population: 0.6,
    prosperity: 58,
    resistance: 55,
    relation: 70,
    garrison: 48,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'sokoto',
    name: 'Sokoto',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'sokoto',
    people: 'Hausa & Fulani emirates',
    economy: 'Sahelian markets',
    good: 'Leather',
    rawMaterial: 'Leather',
    marketDemand: 50,
    isMetropolis: false,
    doctrine: 'Emirate cavalry',
    doctrineDetail: 'Armored cavalry and fortified cities dominate the Sahel.',
    terrain: 'Savanna & Sahel',
    population: 9.0,
    prosperity: 68,
    resistance: 85,
    relation: -6,
    garrison: 69,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'gold-coast',
    name: 'Gold Coast',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'ashanti',
    people: 'Ashanti Empire',
    economy: 'Gold & forest trade',
    good: 'Gold',
    rawMaterial: 'Gold',
    marketDemand: 65,
    isMetropolis: false,
    doctrine: 'Forest envelopment',
    doctrineDetail: 'Wings move unseen through forest to surround columns.',
    terrain: 'Tropical forest',
    population: 3.2,
    prosperity: 73,
    resistance: 91,
    relation: -32,
    garrison: 72,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'dahomey',
    name: 'Dahomey',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'dahomey',
    people: 'Kingdom of Dahomey',
    economy: 'Royal markets',
    good: 'Palm oil',
    rawMaterial: 'Palm oil',
    marketDemand: 60,
    isMetropolis: false,
    doctrine: 'Royal amazon & muskets',
    doctrineDetail: 'Disciplined palace troops and muskets hold the coastal approaches.',
    terrain: 'Coastal savanna',
    population: 0.8,
    prosperity: 62,
    resistance: 86,
    relation: -10,
    garrison: 68,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'slave-coast',
    name: 'Slave Coast',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Coastal forts & Yoruba states',
    economy: 'Palm oil & coastal trade',
    good: 'Palm oil',
    rawMaterial: 'Palm oil',
    marketDemand: 64,
    isMetropolis: false,
    doctrine: 'Coastal forts',
    doctrineDetail: 'Thin British garrisons cling to forts behind Indigenous power.',
    terrain: 'Lagoon coast',
    population: 1.2,
    prosperity: 60,
    resistance: 70,
    relation: 45,
    garrison: 45,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'ethiopian-highlands',
    name: 'Ethiopian Highlands',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'ethiopia',
    people: 'Ethiopian Empire',
    economy: 'Highland agriculture',
    good: 'Coffee',
    rawMaterial: 'Coffee',
    marketDemand: 35,
    isMetropolis: false,
    doctrine: 'Highland host',
    doctrineDetail: 'Provincial hosts converge through known passes.',
    terrain: 'Escarpments',
    population: 5.4,
    prosperity: 62,
    resistance: 96,
    relation: 6,
    garrison: 75,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'east-africa-coast',
    name: 'East Africa Coast',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'portugal',
    people: 'Swahili cities & Omani influence',
    economy: 'Ivory & clove trade',
    good: 'Ivory',
    rawMaterial: 'Ivory',
    marketDemand: 58,
    isMetropolis: false,
    doctrine: 'Coastal factories',
    doctrineDetail: 'Stone towns and dhow fleets contest the monsoon coast.',
    terrain: 'Monsoon coast',
    population: 1.5,
    prosperity: 56,
    resistance: 68,
    relation: 15,
    garrison: 42,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'angola',
    name: 'Angola',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'portugal',
    people: 'Portuguese Angola & Ovimbundu',
    economy: 'Slave & ivory coast',
    good: 'Ivory',
    rawMaterial: 'Ivory',
    marketDemand: 55,
    isMetropolis: false,
    doctrine: 'Coastal presidios',
    doctrineDetail: 'Presidios hold the coast; the interior remains contested.',
    terrain: 'Coastal plateau',
    population: 1.0,
    prosperity: 52,
    resistance: 72,
    relation: 40,
    garrison: 46,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'kongo-basin',
    name: 'Kongo Basin',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'kongo',
    people: 'Kongo & Luba polities',
    economy: 'River markets',
    good: 'Copper',
    rawMaterial: 'Copper',
    marketDemand: 38,
    isMetropolis: false,
    doctrine: 'Dispersed resistance',
    doctrineDetail: 'Small formations exploit rivers and forest depth.',
    terrain: 'Equatorial forest',
    population: 4.7,
    prosperity: 51,
    resistance: 94,
    relation: 2,
    garrison: 58,
    ports: 1,
    isCoastal: true,
  },
  {
    id: 'mozambique',
    name: 'Mozambique',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'portugal',
    people: 'Portuguese Mozambique',
    economy: 'Ivory & coastal trade',
    good: 'Ivory',
    rawMaterial: 'Ivory',
    marketDemand: 52,
    isMetropolis: false,
    doctrine: 'Coastal captaincies',
    doctrineDetail: 'Thin captaincies hold ports against inland kingdoms.',
    terrain: 'Coastal plain',
    population: 0.8,
    prosperity: 50,
    resistance: 70,
    relation: 35,
    garrison: 44,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'cape-colony',
    name: 'Cape Colony',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Khoekhoe, Xhosa, settler & Cape communities',
    economy: 'Provisioning port',
    good: 'Wool',
    rawMaterial: 'Wool',
    marketDemand: 60,
    isMetropolis: false,
    doctrine: 'Frontier columns',
    doctrineDetail: 'Mounted infantry project along roads tied to wagon trains.',
    terrain: 'Veld & mountains',
    population: 0.3,
    prosperity: 64,
    resistance: 67,
    relation: 58,
    garrison: 57,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'zulu-kingdom',
    name: 'Zulu Kingdom',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'zulu',
    people: 'Zulu Kingdom',
    economy: 'Cattle & tribute',
    good: 'Cattle',
    rawMaterial: 'Cattle',
    marketDemand: 30,
    isMetropolis: false,
    doctrine: 'Horns of the buffalo',
    doctrineDetail: 'Regiments fix the center while wings complete encirclement.',
    terrain: 'Rolling grassland',
    population: 0.4,
    prosperity: 57,
    resistance: 98,
    relation: -15,
    garrison: 80,
    ports: 0,
    isCoastal: true,
  },
  {
    id: 'merina-kingdom',
    name: 'Madagascar',
    theater: 'Africa',
    path: '',
    label: [0, 0],
    owner: 'merina',
    people: 'Merina Kingdom',
    economy: 'Highland rice & crafts',
    good: 'Rice',
    rawMaterial: 'Rice',
    marketDemand: 42,
    isMetropolis: false,
    doctrine: 'Highland kingdom',
    doctrineDetail: 'Fortified hills and muskets contest the highlands.',
    terrain: 'Highland island',
    population: 2.0,
    prosperity: 58,
    resistance: 80,
    relation: 5,
    garrison: 62,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'qajar-iran',
    name: 'Qajar Iran',
    theater: 'Asia',
    path: '',
    label: [0, 0],
    owner: 'qajar',
    people: 'Qajar Iran',
    economy: 'Silk & caravan trade',
    good: 'Silk',
    rawMaterial: 'Silk',
    marketDemand: 45,
    isMetropolis: false,
    doctrine: 'Tribal cavalry',
    doctrineDetail: 'Tribal horse and fortress towns guard the plateau.',
    terrain: 'Iranian plateau',
    population: 6.0,
    prosperity: 55,
    resistance: 70,
    relation: 0,
    garrison: 60,
    ports: 1,
    isCoastal: false,
  },
  {
    id: 'afghan-emirate',
    name: 'Afghanistan',
    theater: 'Asia',
    path: '',
    label: [0, 0],
    owner: 'afghanistan',
    people: 'Emirate of Afghanistan',
    economy: 'Caravan tolls',
    good: 'Horses',
    rawMaterial: 'Horses',
    marketDemand: 28,
    isMetropolis: false,
    doctrine: 'Mountain emirates',
    doctrineDetail: 'Passes and tribal levies bleed invading columns.',
    terrain: 'Hindu Kush',
    population: 2.5,
    prosperity: 48,
    resistance: 92,
    relation: -5,
    garrison: 70,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'punjab',
    name: 'Punjab',
    theater: 'India',
    path: '',
    label: [0, 0],
    owner: 'sikh',
    people: 'Sikh Empire',
    economy: 'Irrigated agriculture',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 55,
    isMetropolis: false,
    doctrine: 'Khalsa combined arms',
    doctrineDetail: 'Drilled infantry, guns, and cavalry as a field army.',
    terrain: 'Five rivers plain',
    population: 12.0,
    prosperity: 76,
    resistance: 84,
    relation: -21,
    garrison: 86,
    ports: 0,
    isCoastal: false,
  },
  {
    id: 'bengal',
    name: 'Bengal Presidency',
    theater: 'India',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Bengali communities under Company rule',
    economy: 'Textiles & revenue',
    good: 'Indigo',
    rawMaterial: 'Indigo',
    marketDemand: 75,
    isMetropolis: false,
    doctrine: 'Sepoy field army',
    doctrineDetail: 'Locally recruited infantry defend river magazines.',
    terrain: 'River delta',
    population: 40.0,
    prosperity: 71,
    resistance: 49,
    relation: 48,
    garrison: 70,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'deccan',
    name: 'Deccan',
    theater: 'India',
    path: '',
    label: [0, 0],
    owner: 'maratha',
    people: 'Maratha Confederacy',
    economy: 'Cotton & inland tolls',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 58,
    isMetropolis: false,
    doctrine: 'Mobile campaigning',
    doctrineDetail: 'Fast cavalry threatens communications; hill forts absorb time.',
    terrain: 'Plateau & hill forts',
    population: 18.0,
    prosperity: 67,
    resistance: 89,
    relation: -35,
    garrison: 74,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'madras-coast',
    name: 'Madras Coast',
    theater: 'India',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Company Madras Presidency',
    economy: 'Cotton & coastal trade',
    good: 'Cotton',
    rawMaterial: 'Cotton',
    marketDemand: 70,
    isMetropolis: false,
    doctrine: 'Sepoy garrisons',
    doctrineDetail: 'Coastal arsenals feed inland columns.',
    terrain: 'Coromandel coast',
    population: 8.0,
    prosperity: 68,
    resistance: 45,
    relation: 50,
    garrison: 62,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'konbaung-burma',
    name: 'Konbaung Burma',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'burma',
    people: 'Konbaung Dynasty',
    economy: 'Teak & rice',
    good: 'Teak',
    rawMaterial: 'Teak',
    marketDemand: 40,
    isMetropolis: false,
    doctrine: 'Stockade warfare',
    doctrineDetail: 'Timber stockades and monsoon rivers halt linear advances.',
    terrain: 'Jungle river valleys',
    population: 4.0,
    prosperity: 60,
    resistance: 87,
    relation: -23,
    garrison: 67,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'siam',
    name: 'Siam',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'siam',
    people: 'Kingdom of Siam',
    economy: 'Rice & entrepôt trade',
    good: 'Rice',
    rawMaterial: 'Rice',
    marketDemand: 48,
    isMetropolis: false,
    doctrine: 'Royal army',
    doctrineDetail: 'Matchlocks, spears, and elephant corps defend the Chao Phraya.',
    terrain: 'River plain',
    population: 4.5,
    prosperity: 62,
    resistance: 75,
    relation: 5,
    garrison: 60,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'dai-nam',
    name: 'Đại Nam',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'vietnam',
    people: 'Nguyễn Đại Nam',
    economy: 'Rice & court workshops',
    good: 'Rice',
    rawMaterial: 'Rice',
    marketDemand: 46,
    isMetropolis: false,
    doctrine: 'Citadel defence',
    doctrineDetail: 'Citadels and matchlock troops hold the Red River and Mekong.',
    terrain: 'Monsoon coasts',
    population: 5.0,
    prosperity: 60,
    resistance: 78,
    relation: 0,
    garrison: 62,
    ports: 2,
    isCoastal: true,
  },
  {
    id: 'south-china',
    name: 'South China',
    theater: 'China',
    path: '',
    label: [0, 0],
    owner: 'qing',
    people: 'Great Qing',
    economy: 'Tea & porcelain',
    good: 'Tea',
    rawMaterial: 'Tea',
    marketDemand: 70,
    isMetropolis: false,
    doctrine: 'Banner & Green Standard',
    doctrineDetail: 'Walled cities, river fleets, and deep magazines.',
    terrain: 'River basins',
    population: 145.0,
    prosperity: 79,
    resistance: 82,
    relation: -27,
    garrison: 80,
    ports: 5,
    isCoastal: true,
  },
  {
    id: 'north-china',
    name: 'North China',
    theater: 'China',
    path: '',
    label: [0, 0],
    owner: 'qing',
    people: 'Great Qing',
    economy: 'Grain & administration',
    good: 'Silk',
    rawMaterial: 'Silk',
    marketDemand: 55,
    isMetropolis: false,
    doctrine: 'Fortified strategic depth',
    doctrineDetail: 'Walled cities trade distance for time.',
    terrain: 'Northern plain',
    population: 165.0,
    prosperity: 75,
    resistance: 79,
    relation: -31,
    garrison: 85,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'tokugawa-japan',
    name: 'Japan',
    theater: 'East Asia',
    path: '',
    label: [0, 0],
    owner: 'japan',
    people: 'Tokugawa Shogunate',
    economy: 'Rice, crafts & coastal trade',
    good: 'Lacquerware',
    rawMaterial: 'Lacquerware',
    marketDemand: 40,
    isMetropolis: false,
    doctrine: 'Domain armies',
    doctrineDetail: 'Matchlocks, spears, and coastal batteries.',
    terrain: 'Archipelago',
    population: 30.0,
    prosperity: 72,
    resistance: 70,
    relation: 0,
    garrison: 75,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'java',
    name: 'Java',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'netherlands',
    people: 'Javanese states under Company rule',
    economy: 'Cultivation system',
    good: 'Spices',
    rawMaterial: 'Spices',
    marketDemand: 72,
    isMetropolis: false,
    doctrine: 'Fortified districts',
    doctrineDetail: 'Colonial garrisons hold roads and plantations.',
    terrain: 'Volcanic interior',
    population: 8.5,
    prosperity: 69,
    resistance: 71,
    relation: -12,
    garrison: 59,
    ports: 4,
    isCoastal: true,
  },
  {
    id: 'philippines',
    name: 'Philippines',
    theater: 'Southeast Asia',
    path: '',
    label: [0, 0],
    owner: 'spain',
    people: 'Spanish Philippines',
    economy: 'Galleon & tobacco colony',
    good: 'Tobacco',
    rawMaterial: 'Tobacco',
    marketDemand: 60,
    isMetropolis: false,
    doctrine: 'Colonial garrison',
    doctrineDetail: 'Manila galleon forts and native auxiliaries.',
    terrain: 'Archipelago',
    population: 3.5,
    prosperity: 58,
    resistance: 65,
    relation: 25,
    garrison: 50,
    ports: 3,
    isCoastal: true,
  },
  {
    id: 'australia',
    name: 'Australia',
    theater: 'Pacific',
    path: '',
    label: [0, 0],
    owner: 'britain',
    people: 'Aboriginal nations & British settlements',
    economy: 'Wool & penal colony',
    good: 'Wool',
    rawMaterial: 'Wool',
    marketDemand: 45,
    isMetropolis: false,
    doctrine: 'Colonial outposts',
    doctrineDetail: 'Thin settlements cling to the coast against a vast interior.',
    terrain: 'Arid continent',
    population: 0.5,
    prosperity: 48,
    resistance: 75,
    relation: 40,
    garrison: 40,
    ports: 2,
    isCoastal: true,
  },
]

export const createOpeningEvents = (): CampaignEvent[] => [
  {
    id: 1,
    type: 'world',
    title: 'The colonial scramble',
    body: 'Britain, France, Spain, Portugal, the Netherlands, and the United States race to plant flags, extract raw materials, and flood colonial markets with manufactured goods.',
    turn: 1,
  },
  {
    id: 2,
    type: 'trade',
    title: 'Mercantile orders',
    body: 'Colonial raw materials are to be shipped home. Mills will turn them into finished goods for sale back into colonial markets.',
    turn: 1,
  },
  {
    id: 3,
    type: 'conflict',
    title: 'Gunpowder frontiers',
    body: 'Regular colonial columns with muskets and field guns face Indigenous nations fighting with spears, shields, bows, and whatever trade firearms they can obtain.',
    turn: 1,
  },
]
