import type { Region } from './types'

export type WeaponVisual =
  | 'flintlock'
  | 'rifle'
  | 'trade-musket'
  | 'long-dane'
  | 'matchlock'
  | 'lance'
  | 'iklwa'
  | 'bow'
  | 'sword'

export type HeadgearVisual =
  | 'bell-shako'
  | 'shako'
  | 'forage-cap'
  | 'turban'
  | 'headband'
  | 'war-cap'
  | 'headring'
  | 'conical-hat'
  | 'headwrap'
  | 'knit-cap'
  | 'fez'
  | 'fur-hat'
  | 'jingasa'

export interface MilitaryProfile {
  factionId: string
  forceName: string
  dateRange: string
  attire: string
  weapons: string
  sourceLabel: string
  sourceUrl: string
  coat: string
  coatSecondary: string
  trousers: string
  trim: string
  headgear: HeadgearVisual
  primaryWeapon: WeaponVisual
  secondaryWeapon: WeaponVisual
  skinTones: string[]
  firearmRatio: number
  mountedRatio: number
  shield?: 'round' | 'oval' | 'zulu'
}

export type BattleMapKind = 'woodland' | 'prairie' | 'highlands' | 'river' | 'savanna' | 'fortified'

export const battleMapDetails: Record<BattleMapKind, { name: string; condition: string }> = {
  woodland: { name: 'Forest road', condition: 'Dense cover · short sight lines' },
  prairie: { name: 'Open prairie', condition: 'Long sight lines · strong crosswind' },
  highlands: { name: 'Mountain pass', condition: 'Broken ground · steep approaches' },
  river: { name: 'River crossing', condition: 'Wet powder risk · narrow ford' },
  savanna: { name: 'Rolling grassland', condition: 'Dry ground · heat haze' },
  fortified: { name: 'Walled approaches', condition: 'Prepared works · restricted lanes' },
}

export function getBattleMapKind(region: Region): BattleMapKind {
  const context = `${region.terrain} ${region.doctrine}`.toLowerCase()
  if (/(forest|woodland|jungle|rainforest)/.test(context)) return 'woodland'
  if (/(river|delta|lake|wetland|waterway)/.test(context)) return 'river'
  if (/(mountain|highland|plateau|escarpment|andes|hill fort)/.test(context)) return 'highlands'
  if (/(prairie|steppe|open plain)/.test(context)) return 'prairie'
  if (/(savanna|grassland|veld)/.test(context)) return 'savanna'
  return 'fortified'
}

export const militaryProfiles: Record<string, MilitaryProfile> = {
  unitedStates: {
    factionId: 'unitedStates',
    forceName: 'Army of the West',
    dateRange: 'Mexican–American War kit · 1846',
    attire: 'Sky-blue wool fatigue jackets and trousers, white infantry trim, dark-blue forage caps',
    weapons: 'Model 1816/1822 flintlock muskets; limited M1841 rifles and dragoon carbines',
    sourceLabel: 'U.S. National Park Service · Palo Alto study',
    sourceUrl: 'https://npshistory.com/series/archeology/scrc/52/chap4.htm',
    coat: '#6e9ab6',
    coatSecondary: '#27435f',
    trousers: '#88afc5',
    trim: '#e4e2cf',
    headgear: 'forage-cap',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'rifle',
    skinTones: ['#d8aa82', '#b97c59', '#8a573f', '#e0b895'],
    firearmRatio: 0.94,
    mountedRatio: 0.1,
  },
  britain: {
    factionId: 'britain',
    forceName: 'Royal Field Column',
    dateRange: 'British line infantry kit · 1836',
    attire: 'Red coatees, white crossbelts, dark trousers, and the 1829 bell-topped shako',
    weapons: 'India Pattern “Brown Bess” flintlock muskets with bayonets; light-company rifles',
    sourceLabel: 'Museum of the Manchester Regiment',
    sourceUrl: 'https://www.tameside.gov.uk/librariesandleisure/museumsandgalleries/museum-of-the-manchester-regiment-object-focus-bel',
    coat: '#a83f38',
    coatSecondary: '#272e31',
    trousers: '#d4d1be',
    trim: '#eee5cf',
    headgear: 'bell-shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'rifle',
    skinTones: ['#d8aa82', '#b97c59', '#8a573f', '#e0b895'],
    firearmRatio: 0.97,
    mountedRatio: 0.06,
  },
  france: {
    factionId: 'france',
    forceName: 'Armée d’Afrique',
    dateRange: 'French line kit · 1830s',
    attire: 'Dark-blue coatees, red facings and trousers, leather crossbelts, tall shakos',
    weapons: 'Model 1822 flintlock muskets with socket bayonets and light field guns',
    sourceLabel: 'Musée de l’Armée · period pattern',
    sourceUrl: 'https://www.musee-armee.fr/',
    coat: '#294f78',
    coatSecondary: '#8b3230',
    trousers: '#9b3a36',
    trim: '#e4d7b8',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#d7a780', '#b97a57', '#8f5b42'],
    firearmRatio: 0.94,
    mountedRatio: 0.09,
  },
  portugal: {
    factionId: 'portugal',
    forceName: 'Exército Real',
    dateRange: 'Portuguese line kit · 1830s',
    attire: 'Dark-blue coatees, white trousers and crossbelts, black shakos',
    weapons: 'British-pattern flintlock muskets, bayonets, and cavalry sabres',
    sourceLabel: 'Museu Militar de Lisboa · period pattern',
    sourceUrl: 'https://www.exercito.pt/pt/quem-somos/cultura/museus',
    coat: '#344f70',
    coatSecondary: '#f0ede0',
    trousers: '#ded9c6',
    trim: '#d7bd64',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#d4a078', '#ae714f', '#81523b'],
    firearmRatio: 0.9,
    mountedRatio: 0.08,
  },
  netherlands: {
    factionId: 'netherlands',
    forceName: 'Colonial Field Force',
    dateRange: 'Dutch colonial kit · 1830s',
    attire: 'Dark-blue jackets, white crossbelts and trousers, shako with orange distinctions',
    weapons: 'Flintlock infantry muskets, carbines, and light artillery',
    sourceLabel: 'Nationaal Militair Museum · period pattern',
    sourceUrl: 'https://www.nmm.nl/',
    coat: '#263f59',
    coatSecondary: '#bd6a37',
    trousers: '#d8d3bf',
    trim: '#d88748',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#d8aa82', '#a86c4c', '#7b4d38'],
    firearmRatio: 0.92,
    mountedRatio: 0.05,
  },
  haudenosaunee: {
    factionId: 'haudenosaunee',
    forceName: 'Confederacy Defenders',
    dateRange: 'Haudenosaunee field dress · 1840s',
    attire: 'Trade-cloth shirts and coats, fitted leggings, moccasins, sashes, and headscarves',
    weapons: 'Trade muskets and rifles alongside bows, tomahawks, and war clubs',
    sourceLabel: 'New York State Museum · Morgan Collection',
    sourceUrl: 'https://nysm.nysed.gov/native-american-ethnography/collections/lewis-henry-morgan-collection-mid-nineteenth-century',
    coat: '#315f55',
    coatSecondary: '#873f38',
    trousers: '#3d4d43',
    trim: '#d5b560',
    headgear: 'headband',
    primaryWeapon: 'trade-musket',
    secondaryWeapon: 'bow',
    skinTones: ['#a66545', '#8d5138', '#bc7a55'],
    firearmRatio: 0.66,
    mountedRatio: 0.04,
  },
  coastSalish: {
    factionId: 'coastSalish',
    forceName: 'River Defenders',
    dateRange: 'Coast Salish field dress · 1830s',
    attire: 'Woven wool and trade-cloth garments suited to the wet coastal climate',
    weapons: 'Trade muskets, bows, clubs, and canoe-borne raiding parties',
    sourceLabel: 'Museum-curated regional synthesis',
    sourceUrl: 'https://www.burkemuseum.org/collections-and-research/culture/contemporary-culture/coast-salish-art',
    coat: '#456e73',
    coatSecondary: '#70463b',
    trousers: '#4a3c34',
    trim: '#c9ae72',
    headgear: 'headband',
    primaryWeapon: 'trade-musket',
    secondaryWeapon: 'bow',
    skinTones: ['#a86647', '#8e5239', '#bd7b57'],
    firearmRatio: 0.48,
    mountedRatio: 0,
  },
  lakota: {
    factionId: 'lakota',
    forceName: 'Lakota Akíčhita',
    dateRange: 'Northern Plains field dress · 1840s',
    attire: 'Hide shirts and leggings with quillwork, wool trade cloth, moccasins, and practical headbands',
    weapons: 'Northwest trade muskets, horn bows, long lances, and knives; most fighters mounted',
    sourceLabel: 'Brooklyn Museum & Plains Indian Museum',
    sourceUrl: 'https://www.brooklynmuseum.org/objects/63413',
    coat: '#a77b50',
    coatSecondary: '#36596b',
    trousers: '#876440',
    trim: '#d9bc79',
    headgear: 'headband',
    primaryWeapon: 'trade-musket',
    secondaryWeapon: 'lance',
    skinTones: ['#a66545', '#8d5138', '#bb7650'],
    firearmRatio: 0.48,
    mountedRatio: 0.72,
  },
  mexico: {
    factionId: 'mexico',
    forceName: 'Ejército Mexicano',
    dateRange: 'Mexican republican kit · 1846',
    attire: 'Dark-blue coatees with red facings, white crossbelts, light trousers, and shakos',
    weapons: 'British-pattern flintlock muskets, cavalry lances, and well-served field artillery',
    sourceLabel: 'Palo Alto Battlefield NHS · period synthesis',
    sourceUrl: 'https://www.nps.gov/paal/learn/historyculture/mexican-war.htm',
    coat: '#294d68',
    coatSecondary: '#8b3430',
    trousers: '#d7d2bc',
    trim: '#d6b45c',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#b97852', '#955b3f', '#d09a70'],
    firearmRatio: 0.84,
    mountedRatio: 0.18,
  },
  granColombia: {
    factionId: 'granColombia',
    forceName: 'Republican Field Army',
    dateRange: 'Northern Andean republican kit · 1830s',
    attire: 'Blue wool jackets, red facings, pale trousers, leather belts, and campaign caps',
    weapons: 'Flintlock muskets, sabres, lances, and mountain guns',
    sourceLabel: 'Regional military-history synthesis',
    sourceUrl: 'https://museonacional.gov.co/',
    coat: '#335a79',
    coatSecondary: '#9e4038',
    trousers: '#c8c2a9',
    trim: '#d9bc58',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#a86647', '#8b5139', '#ca8b62', '#6f4636'],
    firearmRatio: 0.8,
    mountedRatio: 0.16,
  },
  tupinamba: {
    factionId: 'tupinamba',
    forceName: 'River Confederacy War Parties',
    dateRange: 'Amazonian river equipment · 1830s',
    attire: 'Locally woven and trade-cloth garments adapted to heat and river travel',
    weapons: 'Powerful bows, spears, clubs, and a limited number of traded firearms',
    sourceLabel: 'Regional material-culture synthesis',
    sourceUrl: 'https://pib.socioambiental.org/',
    coat: '#56735b',
    coatSecondary: '#8d493b',
    trousers: '#5b4934',
    trim: '#cfaa5f',
    headgear: 'headband',
    primaryWeapon: 'bow',
    secondaryWeapon: 'trade-musket',
    skinTones: ['#9d5c3d', '#7f4935', '#b46e49'],
    firearmRatio: 0.2,
    mountedRatio: 0,
  },
  brazil: {
    factionId: 'brazil',
    forceName: 'Imperial Brazilian Army',
    dateRange: 'Brazilian imperial kit · 1830s',
    attire: 'Dark-blue coats, white trousers and belts, shakos with imperial distinctions',
    weapons: 'Flintlock muskets, cavalry sabres, lances, and coastal artillery',
    sourceLabel: 'Museu Histórico Nacional · period synthesis',
    sourceUrl: 'https://mhn.museus.gov.br/',
    coat: '#274b64',
    coatSecondary: '#65783e',
    trousers: '#d8d2bd',
    trim: '#d4b952',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#cf986f', '#9b6044', '#704737', '#b77b58'],
    firearmRatio: 0.84,
    mountedRatio: 0.14,
  },
  andean: {
    factionId: 'andean',
    forceName: 'Andean Community Levies',
    dateRange: 'Andean highland field dress · 1830s',
    attire: 'Wool tunics and ponchos, fitted trousers, sandals, and knitted caps',
    weapons: 'Slings, spears, locally held muskets, and captured republican arms',
    sourceLabel: 'Andean textile and arms synthesis',
    sourceUrl: 'https://museolarco.org/en/',
    coat: '#80584d',
    coatSecondary: '#48677a',
    trousers: '#6c4f3d',
    trim: '#d4a65a',
    headgear: 'knit-cap',
    primaryWeapon: 'trade-musket',
    secondaryWeapon: 'lance',
    skinTones: ['#9c5b3e', '#804936', '#b46f4c'],
    firearmRatio: 0.38,
    mountedRatio: 0.04,
  },
  mapuche: {
    factionId: 'mapuche',
    forceName: 'Mapuche Weichafe',
    dateRange: 'Wallmapu field dress · 1840s',
    attire: 'Heavy wool makuñ ponchos, woven belts, headbands, riding trousers, and boots',
    weapons: 'Long cavalry lances, bolas, swords, and acquired flintlock firearms',
    sourceLabel: 'Textile Museum of Canada · trarikanmakuñ',
    sourceUrl: 'https://textilemuseum.ca/collection/poncho-t92-0262/',
    coat: '#713e45',
    coatSecondary: '#334f68',
    trousers: '#493d39',
    trim: '#c8a45d',
    headgear: 'headband',
    primaryWeapon: 'lance',
    secondaryWeapon: 'trade-musket',
    skinTones: ['#9d5b3f', '#7f4936', '#b46f4c'],
    firearmRatio: 0.36,
    mountedRatio: 0.62,
  },
  sokoto: {
    factionId: 'sokoto',
    forceName: 'Emirate Field Host',
    dateRange: 'Sokoto field equipment · 1830s',
    attire: 'Indigo or cream robes, turbans, leather equipment, and quilted cavalry armor',
    weapons: 'Lances, swords, bows, and imported flintlock muskets',
    sourceLabel: 'West African military-history synthesis',
    sourceUrl: 'https://www.britishmuseum.org/collection',
    coat: '#415d76',
    coatSecondary: '#d1c59f',
    trousers: '#b9ae8a',
    trim: '#c89e4e',
    headgear: 'turban',
    primaryWeapon: 'lance',
    secondaryWeapon: 'flintlock',
    skinTones: ['#70432f', '#563325', '#88523a', '#9c6244'],
    firearmRatio: 0.34,
    mountedRatio: 0.42,
  },
  ashanti: {
    factionId: 'ashanti',
    forceName: 'Asante Field Army',
    dateRange: 'Asante field dress · 1820s–1840s',
    attire: 'Cotton batakari war smocks, leather ntoa cartridge belts, powder vessels, and cloth caps',
    weapons: 'Long Dane trade muskets fired in close forest volleys, plus swords and knives',
    sourceLabel: 'Drury University collection & Journal of African History',
    sourceUrl: 'http://artcollection.drury.edu/items/show/2311',
    coat: '#a06d38',
    coatSecondary: '#66513c',
    trousers: '#5f4935',
    trim: '#dfbf66',
    headgear: 'war-cap',
    primaryWeapon: 'long-dane',
    secondaryWeapon: 'sword',
    skinTones: ['#70432f', '#563325', '#875139', '#9b6042'],
    firearmRatio: 0.91,
    mountedRatio: 0,
  },
  ethiopia: {
    factionId: 'ethiopia',
    forceName: 'Ethiopian Provincial Host',
    dateRange: 'Ethiopian highland kit · 1830s',
    attire: 'White shamma wraps, cotton trousers, headcloths, leather belts, and hide shields',
    weapons: 'Spears, curved shotel swords, round shields, and mixed matchlock or flintlock guns',
    sourceLabel: 'Ethiopian material-culture synthesis',
    sourceUrl: 'https://www.britishmuseum.org/collection/galleries/africa',
    coat: '#d2c8a8',
    coatSecondary: '#8d4f45',
    trousers: '#bfb594',
    trim: '#d5ad55',
    headgear: 'headwrap',
    primaryWeapon: 'lance',
    secondaryWeapon: 'matchlock',
    skinTones: ['#815039', '#68402e', '#985f42'],
    firearmRatio: 0.42,
    mountedRatio: 0.12,
    shield: 'round',
  },
  kongo: {
    factionId: 'kongo',
    forceName: 'Kongo River Companies',
    dateRange: 'Kongo Basin field equipment · 1830s',
    attire: 'Locally woven cloth, trade-cloth jackets, headwraps, and leather ammunition pouches',
    weapons: 'Trade muskets, spears, swords, and river-borne raiding craft',
    sourceLabel: 'Central African material-culture synthesis',
    sourceUrl: 'https://www.metmuseum.org/art/collection/search#!?searchField=All&showOnly=withImage&material=Kongo',
    coat: '#735b7b',
    coatSecondary: '#9b6b44',
    trousers: '#4d4439',
    trim: '#d0b566',
    headgear: 'headwrap',
    primaryWeapon: 'trade-musket',
    secondaryWeapon: 'lance',
    skinTones: ['#6b402e', '#533225', '#845039', '#9a6042'],
    firearmRatio: 0.52,
    mountedRatio: 0,
  },
  zulu: {
    factionId: 'zulu',
    forceName: 'Royal Amabutho',
    dateRange: 'Zulu regimental kit · 1830s',
    attire: 'Regimental cow-tail ornaments and fur distinctions with color-matched cowhide shields',
    weapons: 'Large isihlangu shields, short broad-bladed iklwa, throwing spears, and knobkerries',
    sourceLabel: 'Ditsong Museums of South Africa',
    sourceUrl: 'https://ditsong.org.za/en/amabutho-akwazulu-the-royal-patronage-since-the-pre-shakan-era/',
    coat: '#6d4c35',
    coatSecondary: '#342b25',
    trousers: '#49362a',
    trim: '#e2d0a5',
    headgear: 'headring',
    primaryWeapon: 'iklwa',
    secondaryWeapon: 'lance',
    skinTones: ['#70432f', '#573326', '#875039', '#9a5f42'],
    firearmRatio: 0.03,
    mountedRatio: 0,
    shield: 'zulu',
  },
  sikh: {
    factionId: 'sikh',
    forceName: 'Khalsa Fauj-i-Khas',
    dateRange: 'Khalsa regular infantry · 1836',
    attire: 'Scarlet French-cut coatees or white uniforms, black crossbelts, white trousers, red or yellow turbans',
    weapons: 'Lahore-made flintlock muskets and bayonets, tulwars, lances, and horse artillery',
    sourceLabel: 'Wallace Collection & Sikh Museum',
    sourceUrl: 'https://www.wallacecollection.org/explore/explore-in-depth/the-sikh-empire/sikh-arms-armour/ranjit-singhs-army-his-firangis/',
    coat: '#a13f36',
    coatSecondary: '#e0d6b9',
    trousers: '#d8d1b8',
    trim: '#d6b44f',
    headgear: 'turban',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#a76645', '#895139', '#bc7953', '#744735'],
    firearmRatio: 0.9,
    mountedRatio: 0.16,
  },
  maratha: {
    factionId: 'maratha',
    forceName: 'Maratha Field Confederacy',
    dateRange: 'Maratha field dress · 1830s',
    attire: 'White cotton angarkha coats and trousers, colored waist sashes, turbans, and leather belts',
    weapons: 'Matchlocks, tulwars, long cavalry lances, and hill-fort artillery',
    sourceLabel: 'Indian arms and dress synthesis',
    sourceUrl: 'https://csmvs.in/',
    coat: '#d1c7a7',
    coatSecondary: '#a44c38',
    trousers: '#bfb697',
    trim: '#dc9b42',
    headgear: 'turban',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'sword',
    skinTones: ['#9b5d40', '#7d4936', '#b8744f'],
    firearmRatio: 0.62,
    mountedRatio: 0.34,
  },
  burma: {
    factionId: 'burma',
    forceName: 'Konbaung Royal Army',
    dateRange: 'Konbaung field dress · 1830s',
    attire: 'Cotton jackets, patterned paso wraps, headcloths, and lacquered or woven equipment',
    weapons: 'Muskets, dha swords, spears, jingal wall-guns, stockades, and war elephants',
    sourceLabel: 'Konbaung military-history synthesis',
    sourceUrl: 'https://www.britishmuseum.org/collection',
    coat: '#7d4d5c',
    coatSecondary: '#c09155',
    trousers: '#684d40',
    trim: '#d4b35d',
    headgear: 'headwrap',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'sword',
    skinTones: ['#a56545', '#895038', '#bc7953'],
    firearmRatio: 0.58,
    mountedRatio: 0.02,
  },
  qing: {
    factionId: 'qing',
    forceName: 'Green Standard & Banner Force',
    dateRange: 'Qing field equipment · 1830s',
    attire: 'Dark-blue cotton jackets with bordered panels and conical woven or leather military hats',
    weapons: 'Matchlock muskets, composite bows, spears, sabres, shields, and jingal wall-guns',
    sourceLabel: 'Hong Kong Palace Museum · Qing armaments',
    sourceUrl: 'https://www.hkpm.org.hk/en/exhibition/the-hong-kong-jockey-club-series-the-art-of-armaments-qing-dynasty-military-collection-from-the-palace-museum',
    coat: '#315b62',
    coatSecondary: '#273d46',
    trousers: '#30383a',
    trim: '#c54f43',
    headgear: 'conical-hat',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'bow',
    skinTones: ['#b97852', '#9d6042', '#cf9166'],
    firearmRatio: 0.42,
    mountedRatio: 0.08,
    shield: 'round',
  },
  spain: {
    factionId: 'spain',
    forceName: 'Ejército Real',
    dateRange: 'Spanish line infantry · 1830s',
    attire: 'Dark-blue coatees, red facings, white crossbelts, grey trousers, and tall shakos',
    weapons: 'Flintlock muskets with bayonets, cavalry sabres, and field artillery',
    sourceLabel: 'Museo del Ejército · period synthesis',
    sourceUrl: 'https://ejercito.defensa.gob.es/museo/',
    coat: '#304c69',
    coatSecondary: '#883832',
    trousers: '#aaa99d',
    trim: '#e5d6b3',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#c98c65', '#a76849', '#dfab83'],
    firearmRatio: 0.9,
    mountedRatio: 0.08,
  },
  russia: {
    factionId: 'russia',
    forceName: 'Russian Imperial Army',
    dateRange: 'Russian line infantry · 1830s',
    attire: 'Dark-green coatees, white summer trousers, leather crossbelts, and 1828-pattern shakos',
    weapons: 'Flintlock infantry muskets, socket bayonets, cavalry sabres, and massed batteries',
    sourceLabel: 'State Hermitage · military collection synthesis',
    sourceUrl: 'https://www.hermitagemuseum.org/',
    coat: '#315443',
    coatSecondary: '#202c29',
    trousers: '#d2ceb9',
    trim: '#c64a3e',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#d5a17a', '#b77956', '#e2b38e'],
    firearmRatio: 0.94,
    mountedRatio: 0.12,
  },
  prussia: {
    factionId: 'prussia',
    forceName: 'Prussian Field Army',
    dateRange: 'Prussian line infantry · 1830s',
    attire: 'Dark-blue coatees, grey trousers, white belts, and black shakos with brass plates',
    weapons: 'Potsdam flintlock muskets, bayonets, cavalry sabres, and disciplined field batteries',
    sourceLabel: 'Deutsches Historisches Museum · period synthesis',
    sourceUrl: 'https://www.dhm.de/',
    coat: '#263f5b',
    coatSecondary: '#22282b',
    trousers: '#777a75',
    trim: '#e0d6ba',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#d7a67f', '#b87956', '#e1b48f'],
    firearmRatio: 0.97,
    mountedRatio: 0.09,
  },
  austria: {
    factionId: 'austria',
    forceName: 'Austrian Imperial Army',
    dateRange: 'Austrian line infantry · 1830s',
    attire: 'White coatees with colored facings, pale-blue trousers, crossbelts, and black shakos',
    weapons: 'Augustin-system muskets, bayonets, lances, and heavy field artillery',
    sourceLabel: 'Heeresgeschichtliches Museum · period synthesis',
    sourceUrl: 'https://www.hgm.at/',
    coat: '#ddd8c5',
    coatSecondary: '#8b4c45',
    trousers: '#a7bac1',
    trim: '#d6b255',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#d5a17a', '#b87955', '#e2b38d'],
    firearmRatio: 0.94,
    mountedRatio: 0.1,
  },
  ottoman: {
    factionId: 'ottoman',
    forceName: 'Asakir-i Mansure',
    dateRange: 'Reformed Ottoman infantry · 1830s',
    attire: 'European-cut dark jackets and trousers with red fezzes, leather belts, and cartridge boxes',
    weapons: 'Flintlock muskets, bayonets, kilij sabres, lances, and reformed artillery',
    sourceLabel: 'Istanbul Military Museum · reform-era synthesis',
    sourceUrl: 'https://muze.gov.tr/muze-detay?SectionId=ASK01',
    coat: '#2e4a5d',
    coatSecondary: '#8d3435',
    trousers: '#323d45',
    trim: '#d2ad55',
    headgear: 'fez',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#b97652', '#965a40', '#d19a72'],
    firearmRatio: 0.88,
    mountedRatio: 0.14,
  },
  morocco: {
    factionId: 'morocco',
    forceName: 'Moroccan Mahalla',
    dateRange: 'Moroccan field host · 1830s',
    attire: 'White or earth-toned wool robes, hooded cloaks, turbans, leather belts, and riding boots',
    weapons: 'Long flintlock muskets, cavalry lances, curved swords, and locally cast guns',
    sourceLabel: 'Musée de l’Armée · North African arms synthesis',
    sourceUrl: 'https://www.musee-armee.fr/',
    coat: '#c5b58e',
    coatSecondary: '#8b4f3c',
    trousers: '#86745a',
    trim: '#d0a54f',
    headgear: 'turban',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#a96848', '#8e523b', '#c3835d'],
    firearmRatio: 0.56,
    mountedRatio: 0.34,
  },
  algeria: {
    factionId: 'algeria',
    forceName: 'Army of Emir Abdelkader',
    dateRange: 'Algerian resistance forces · 1830s',
    attire: 'White burnous cloaks, layered wool garments, turbans, sashes, and cavalry boots',
    weapons: 'Long flintlock muskets, pistols, yataghan swords, and cavalry lances',
    sourceLabel: 'Musée de l’Armée · Algerian campaigns synthesis',
    sourceUrl: 'https://www.musee-armee.fr/',
    coat: '#d1c6a7',
    coatSecondary: '#4e6d5f',
    trousers: '#8d8067',
    trim: '#be9349',
    headgear: 'headwrap',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#a66847', '#8c513a', '#c28059'],
    firearmRatio: 0.68,
    mountedRatio: 0.4,
  },
  egypt: {
    factionId: 'egypt',
    forceName: 'Egyptian Nizam Army',
    dateRange: 'Muhammad Ali’s regular army · 1830s',
    attire: 'White cotton uniforms, red fezzes, dark belts, and European-style cartridge equipment',
    weapons: 'Flintlock muskets and bayonets supported by a large, modern field artillery train',
    sourceLabel: 'National Military Museum of Egypt · period synthesis',
    sourceUrl: 'https://egymonuments.gov.eg/',
    coat: '#d6cfb6',
    coatSecondary: '#8f3836',
    trousers: '#c6bfa9',
    trim: '#b89245',
    headgear: 'fez',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#a96847', '#8d523a', '#c4825c'],
    firearmRatio: 0.92,
    mountedRatio: 0.1,
  },
  dahomey: {
    factionId: 'dahomey',
    forceName: 'Dahomean Royal Army',
    dateRange: 'Dahomean royal regiments · 1830s',
    attire: 'Indigo, red, and earth-toned tunics or wraps with cartridge pouches and unit distinctions',
    weapons: 'Imported flintlock muskets, short swords, long knives, and close-assault weapons',
    sourceLabel: 'Musée du quai Branly · Dahomey collections',
    sourceUrl: 'https://www.quaibranly.fr/',
    coat: '#405c6f',
    coatSecondary: '#914139',
    trousers: '#54463a',
    trim: '#d4a64e',
    headgear: 'headwrap',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#6c402e', '#523124', '#865039', '#985e41'],
    firearmRatio: 0.68,
    mountedRatio: 0,
  },
  merina: {
    factionId: 'merina',
    forceName: 'Merina Royal Army',
    dateRange: 'Merina royal infantry · 1830s',
    attire: 'White or patterned lamba wraps, fitted tunics, headcloths, and European cartridge belts',
    weapons: 'Imported flintlock muskets, spears, swords, and highland field works',
    sourceLabel: 'Musée du quai Branly · Madagascar collections',
    sourceUrl: 'https://www.quaibranly.fr/',
    coat: '#c8bea2',
    coatSecondary: '#754f78',
    trousers: '#746253',
    trim: '#c89f4e',
    headgear: 'headwrap',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#815039', '#673e2e', '#9a6042'],
    firearmRatio: 0.62,
    mountedRatio: 0,
  },
  argentina: {
    factionId: 'argentina',
    forceName: 'Confederation Army',
    dateRange: 'Argentine provincial forces · 1830s',
    attire: 'Blue jackets or ponchos, red federal distinctions, riding trousers, boots, and campaign caps',
    weapons: 'Flintlock carbines and muskets, cavalry lances, sabres, bolas, and light guns',
    sourceLabel: 'Museo Histórico Nacional Argentina · synthesis',
    sourceUrl: 'https://museohistoriconacional.cultura.gob.ar/',
    coat: '#4e7890',
    coatSecondary: '#8e3c38',
    trousers: '#5d5b55',
    trim: '#d2c29c',
    headgear: 'forage-cap',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#c1845e', '#9d6043', '#d49d75'],
    firearmRatio: 0.56,
    mountedRatio: 0.48,
  },
  chile: {
    factionId: 'chile',
    forceName: 'Chilean Republican Army',
    dateRange: 'Chilean line army · 1830s',
    attire: 'Dark-blue coatees, red facings, white crossbelts, grey trousers, and black shakos',
    weapons: 'Flintlock muskets and bayonets, cavalry sabres, lances, and field guns',
    sourceLabel: 'Museo Histórico y Militar de Chile · synthesis',
    sourceUrl: 'https://www.mhm.cl/',
    coat: '#2d4e6e',
    coatSecondary: '#8b3936',
    trousers: '#7e817e',
    trim: '#d9cfb4',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#bd7c57', '#995c40', '#d49b72'],
    firearmRatio: 0.86,
    mountedRatio: 0.14,
  },
  peruBolivia: {
    factionId: 'peruBolivia',
    forceName: 'Confederation Field Army',
    dateRange: 'Peru–Bolivian line army · 1830s',
    attire: 'Dark-blue or green coatees, colored facings, pale trousers, crossbelts, and shakos',
    weapons: 'Flintlock muskets, cavalry lances, sabres, and mountain artillery',
    sourceLabel: 'Andean republican military synthesis',
    sourceUrl: 'https://mnaahp.cultura.pe/',
    coat: '#315a67',
    coatSecondary: '#8c493a',
    trousers: '#b2aa91',
    trim: '#d2af4e',
    headgear: 'shako',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'lance',
    skinTones: ['#ae6d4b', '#8d523a', '#c4825a'],
    firearmRatio: 0.82,
    mountedRatio: 0.16,
  },
  qajar: {
    factionId: 'qajar',
    forceName: 'Qajar Sarbaz',
    dateRange: 'Qajar regular infantry · 1830s',
    attire: 'Dark-blue or red European-cut coats, white belts, trousers, and tall black lambskin hats',
    weapons: 'Flintlock muskets and bayonets alongside swords, lances, and reform-era artillery',
    sourceLabel: 'Royal Armouries & Qajar collection synthesis',
    sourceUrl: 'https://royalarmouries.org/',
    coat: '#3c526b',
    coatSecondary: '#91423b',
    trousers: '#a7a292',
    trim: '#d2aa4b',
    headgear: 'fur-hat',
    primaryWeapon: 'flintlock',
    secondaryWeapon: 'sword',
    skinTones: ['#ab6c4b', '#8d523b', '#c6825b'],
    firearmRatio: 0.72,
    mountedRatio: 0.2,
  },
  afghanistan: {
    factionId: 'afghanistan',
    forceName: 'Afghan Tribal Lashkar',
    dateRange: 'Afghan mountain forces · 1830s',
    attire: 'Layered wool robes, loose trousers, waistcoats, turbans, sashes, and mountain footwear',
    weapons: 'Long-barrelled jezail rifles, swords, shields, and mounted lancers',
    sourceLabel: 'National Army Museum · First Afghan War collections',
    sourceUrl: 'https://collection.nam.ac.uk/',
    coat: '#8a7658',
    coatSecondary: '#4f654e',
    trousers: '#695b48',
    trim: '#c3974b',
    headgear: 'turban',
    primaryWeapon: 'rifle',
    secondaryWeapon: 'sword',
    skinTones: ['#a66747', '#895039', '#bf7c56'],
    firearmRatio: 0.68,
    mountedRatio: 0.26,
    shield: 'round',
  },
  japan: {
    factionId: 'japan',
    forceName: 'Tokugawa Domain Army',
    dateRange: 'Late Edo domain troops · 1830s',
    attire: 'Dark indigo jackets and hakama, lacquered jingasa hats, sashimono banners, and some armor',
    weapons: 'Tanegashima matchlocks, yari spears, bows, swords, and coastal cannon',
    sourceLabel: 'Tokyo National Museum · arms and armor synthesis',
    sourceUrl: 'https://www.tnm.jp/',
    coat: '#2d4b57',
    coatSecondary: '#77505a',
    trousers: '#29383b',
    trim: '#c5a24f',
    headgear: 'jingasa',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'lance',
    skinTones: ['#bd7d58', '#9d6043', '#d29a70'],
    firearmRatio: 0.58,
    mountedRatio: 0.06,
  },
  siam: {
    factionId: 'siam',
    forceName: 'Siamese Royal Army',
    dateRange: 'Siamese royal troops · 1830s',
    attire: 'Cotton jackets or wraps, patterned lower garments, headcloths, belts, and unit-colored sashes',
    weapons: 'Matchlock and flintlock muskets, spears, swords, elephant corps, and fortress guns',
    sourceLabel: 'National Museum Bangkok · period synthesis',
    sourceUrl: 'https://www.finearts.go.th/museum-bangkok',
    coat: '#8a503f',
    coatSecondary: '#d0bd96',
    trousers: '#5f493e',
    trim: '#d6aa4c',
    headgear: 'headwrap',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'lance',
    skinTones: ['#ad6b49', '#8e533a', '#c4815a'],
    firearmRatio: 0.52,
    mountedRatio: 0.02,
  },
  vietnam: {
    factionId: 'vietnam',
    forceName: 'Nguyễn Imperial Army',
    dateRange: 'Nguyễn imperial troops · 1830s',
    attire: 'Dark-blue cotton tunics and trousers, headwraps or conical military hats, and colored waist sashes',
    weapons: 'Matchlock muskets, spears, swords, bows, jingals, and citadel artillery',
    sourceLabel: 'National Museum of Vietnamese History · synthesis',
    sourceUrl: 'https://baotanglichsu.vn/',
    coat: '#385d5b',
    coatSecondary: '#263f42',
    trousers: '#303e3d',
    trim: '#c64e3f',
    headgear: 'conical-hat',
    primaryWeapon: 'matchlock',
    secondaryWeapon: 'lance',
    skinTones: ['#b87550', '#965a40', '#ca8b63'],
    firearmRatio: 0.58,
    mountedRatio: 0.02,
  },
}

export function getMilitaryProfile(factionId: string): MilitaryProfile {
  return militaryProfiles[factionId] ?? militaryProfiles.britain
}
